import assert from "node:assert/strict";
import express from "express";
import type { AddressInfo } from "node:net";
import { randomUUID } from "node:crypto";
import { prisma } from "../src/lib/prisma.js";
import { ensureSystemRoles } from "../src/lib/accessRoles.js";
import { createSession } from "../src/lib/session.js";
import { discoverFields, applyValues, sanitizeValue, buildPreview, safeStyle, versionValues, type FieldValue } from "../src/services/website/index.js";

// Auth must be real for these refusals. Set before importing the middleware.
process.env.DEV_NO_AUTH = "false";
process.env.NODE_ENV = "development";
const { attachUser, requireAuth } = await import("../src/middleware/auth.js");
const { websiteRouter } = await import("../src/routes/website.js");

const html = '<!doctype html><html><head><style>.card{display:grid;gap:2rem}h1{color:rgb(49,87,255)}</style></head><body><main><section class="card" data-dw-field="hero.layout"><h1 data-dw-field="hero.title">Hello world</h1><img src="/original.png" alt="Original image"></section></main><script>window.evil=true</script></body></html>';
const fields = discoverFields(html).fields;
const title = fields.find(field => field.id === "hero.title")!;
assert.equal(title.confidence, "annotated");
assert.equal(title.parentId, "hero.layout");
const draft = sanitizeValue(title, { value: "A new heading" });
const moved = html.replace("<main>", "<main><section><h2>Inserted earlier</h2></section>");
const applied = applyValues(moved, { [title.id]: draft });
assert.equal(applied.conflicts.length, 0);
assert.ok(applied.html.includes('data-dw-field="hero.title">A new heading'));
const container = fields.find(field => field.id === "hero.layout")!;
assert.equal(container.kind, "container");
assert.deepEqual(sanitizeValue(container, { value: "destroy the children" }), {});
const layoutEdit = sanitizeValue(container, { style: "display: flex; gap: 2rem" });
assert.ok(applyValues(html, { [container.id]: layoutEdit }).html.includes('style="display: flex; gap: 2rem"'));
assert.equal(applyValues(html.replace("Hello world", "Developer's update"), { [container.id]: layoutEdit }).conflicts.length, 1);
const duplicated = discoverFields(html.replace('src="/original.png"', 'data-dw-field="hero.title" src="/original.png"')).fields;
assert.equal(duplicated.filter(field => field.id === "hero.title").length, 0);
assert.equal(new Set(duplicated.map(field => field.id)).size, duplicated.length);
assert.equal(safeStyle('font-family: "DM Sans", sans-serif'), 'font-family: "DM Sans", sans-serif');
assert.equal(safeStyle('color: red" onclick="bad()'), "");
const backgroundSource = '<section style="background-image: url(/hero.jpg); padding: 2rem"><h1>Hello</h1></section>';
const backgroundField = discoverFields(backgroundSource).fields.find(field => field.kind === "container")!;
const backgroundEdit = sanitizeValue(backgroundField, { style: "background-image: url(/hero.jpg); padding: 3rem" });
assert.match(applyValues(backgroundSource, { [backgroundField.id]: backgroundEdit }).html, /background-image: url\(\/hero.jpg\); padding: 3rem/);
assert.doesNotMatch(sanitizeValue(backgroundField, { style: "background-image: url(https://new-tracker.test); padding: 3rem" }).style ?? "", /new-tracker/);
const responsiveImage = '<img src="/small.jpg" srcset="/small.jpg 1x, /large.jpg 2x" alt="Original">';
const imageWithCandidates = discoverFields(responsiveImage).fields[0]!;
const newPhoto = sanitizeValue(imageWithCandidates, { value: "/replacement.jpg" });
assert.equal(applyValues(responsiveImage, { [imageWithCandidates.id]: newPhoto }).html, '<img src="/replacement.jpg" srcset="" alt="Original">');
assert.equal(applyValues(responsiveImage.replace("/large.jpg", "/developer.jpg"), { [imageWithCandidates.id]: newPhoto }).conflicts.length, 1);
const buttonSource = '<a class="btn btn-primary" href="/about">About</a>';
const buttonField = discoverFields(buttonSource).fields[0]!;
assert.equal(applyValues(buttonSource.replace('href=', 'target="_blank" href='), { [buttonField.id]: sanitizeValue(buttonField, { value: "About us" }) }).conflicts.length, 1);
const oldStyle = sanitizeValue(title, { style: "color: red" });
assert.equal(oldStyle.originalStyle, "");
assert.equal(applyValues(html.replace('<h1 ', '<h1 style="color: green" '), { [title.id]: oldStyle }).conflicts.length, 1);
const preview = buildPreview(html, "https://example.com", fields);
assert.match(preview.csp, /script-src 'nonce-[^']+'/);
assert.doesNotMatch(preview.csp.match(/script-src[^;]*/)?.[0] ?? "", /unsafe-inline|https:|'self'/);
assert.match(preview.csp, /connect-src 'none'/);
assert.match(preview.csp, /style-src[^;]*'unsafe-inline'/);
const hostilePreview = buildPreview('<html><head><base href="https://wrong.test/"><meta content="0;url=https://wrong.test/?q=>" http-equiv="refresh"><meta content="default-src none" http-equiv="Content-Security-Policy"></head><body><h1>Hello</h1></body></html>', "https://example.com/docs/page.html");
assert.doesNotMatch(hostilePreview.html, /wrong\.test|http-equiv/);
assert.match(hostilePreview.html, /<base href="https:\/\/example.com\/docs\/page.html">/);
assert.match(buildPreview(html, "https://example.com", fields, false).html, /function startEdit\(el\) \{\s*if \(!false\) return;/);

await ensureSystemRoles();
const mark = `editorcheck-${randomUUID()}`;
const ownerRole = await prisma.accessRole.findUniqueOrThrow({ where: { key: "owner" } });
const owner = await prisma.user.create({ data: { email: `${mark}@example.test`, name: "Editor check", role: "OWNER", accessRoleId: ownerRole.id } });
const readRole = await prisma.accessRole.create({ data: { key: mark, name: "Editor test viewer", permissions: ["website.view"] } });
const reader = await prisma.user.create({ data: { email: `${mark}-reader@example.test`, name: "Reader", role: "DEVELOPER", accessRoleId: readRole.id } });
const cookie = `dw_session=${await createSession(owner.id)}`;
const readCookie = `dw_session=${await createSession(reader.id)}`;
const app = express();
app.use(express.json({ limit: "8mb" })); app.use(attachUser); app.use("/api", requireAuth); app.use("/api/website", websiteRouter);
app.use((err: { status?: number; message?: string }, _req: express.Request, res: express.Response, _next: express.NextFunction) => res.status(err.status ?? 500).json({ error: err.message }));
const server = app.listen(0, "127.0.0.1");
await new Promise(resolve => server.once("listening", resolve));
const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}/api/website`;
const ids: string[] = [];
const call = async (method: string, url: string, data?: unknown, session = cookie) => fetch(base + url, { method, headers: { "Content-Type": "application/json", Cookie: session }, body: data === undefined ? undefined : JSON.stringify(data) });
try {
  assert.equal((await call("GET", "/sites", undefined, "")).status, 401);
  assert.equal((await call("POST", "/sites", { name: mark, publicUrl: "https://example.test", html }, readCookie)).status, 403);
  const created = await call("POST", "/sites", { name: mark, publicUrl: "https://example.test", html });
  assert.equal(created.status, 201, await created.clone().text());
  const site = await created.json() as { id: string; pageId: string }; ids.push(site.id);
  const pageUrl = `/pages/${site.pageId}`;
  const read = await (await call("GET", pageUrl)).json() as any;
  assert.equal(read.source, undefined); // No complete source file exposed as JSON.
  assert.ok(read.sections.some((section: { fields: { id: string }[] }) => section.fields.some(field => field.id === title.id)));
  const responsive = { tablet: "font-size: 3rem; line-height: 1.2", mobile: "font-size: 2rem" };
  const rawResponsive = {
    tablet: responsive.tablet,
    mobile: `${responsive.mobile}; background-image: url(https://tracker.example.test/hit); width: expression(alert(1)); color: red}</style><script>window.breakpointInjection=true</script>`,
  };
  const headingEdit = { value: "Saved heading", responsive };
  assert.equal((await call("PUT", `${pageUrl}/draft`, { ifRevision: 0, values: { [title.id]: headingEdit } }, readCookie)).status, 403);
  const savedHeading = await call("PUT", `${pageUrl}/draft`, { ifRevision: 0, values: { [title.id]: { ...headingEdit, responsive: rawResponsive } } });
  assert.equal(savedHeading.status, 200, await savedHeading.clone().text());
  const savedPage = await (await call("GET", pageUrl)).json() as any;
  assert.equal(savedPage.draft.revision, 1);
  assert.deepEqual(savedPage.draft.values[title.id].responsive, responsive);
  const storedDraft = (await prisma.sitePage.findUniqueOrThrow({ where: { id: site.pageId } })).draft as any;
  assert.deepEqual(storedDraft[title.id].responsive, responsive);
  assert.deepEqual(storedDraft[title.id].originalResponsive, {});
  assert.doesNotMatch(JSON.stringify(storedDraft), /tracker\.example|expression|breakpointInjection/);
  assert.equal((await call("PUT", `${pageUrl}/draft`, { ifRevision: 0, values: {} })).status, 409);
  const mineResponsive = { tablet: "font-size: 4rem", mobile: "font-size: 2.5rem" };
  const contestedSave = await call("PUT", `${pageUrl}/draft`, { ifRevision: 0, values: { [title.id]: { value: "Saved heading", responsive: mineResponsive } } });
  assert.equal(contestedSave.status, 409);
  const contested = await contestedSave.json() as any;
  const headingConflict = contested.fields.find((field: { id: string }) => field.id === title.id);
  assert.equal(contested.revision, 1);
  assert.equal(headingConflict.contested, true);
  assert.deepEqual(headingConflict.yours.responsive, mineResponsive);
  assert.deepEqual(headingConflict.theirs.responsive, responsive);
  const review = await (await call("GET", `${pageUrl}/review`)).json() as any;
  assert.equal(review.publishable, true);
  assert.ok(review.summary.some((entry: { to: string }) => entry.to === "Saved heading"));
  for (const [device, styles] of Object.entries(responsive)) {
    const label = device === "mobile" ? "phone" : device;
    assert.ok(review.summary.some((entry: { id: string; part: string; label: string; to: string }) => entry.id === title.id && `${entry.part} ${entry.label}`.toLowerCase().includes(label) && entry.to === styles), `${device} styling must appear in the publish review`);
  }
  assert.equal((await call("POST", `${pageUrl}/publish`, { ifRevision: 0, sourceHash: review.sourceHash })).status, 409);
  const png = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5xkAAAAASUVORK5CYII=";
  assert.equal((await call("POST", `/sites/${site.id}/assets`, { filename: "fake.png", data: Buffer.from("<script>evil</script>").toString("base64") })).status, 400);
  const assetResponse = await call("POST", `/sites/${site.id}/assets`, { filename: "pixel.png", data: png, alt: "Pixel" });
  assert.equal(assetResponse.status, 201, await assetResponse.clone().text());
  const asset = await assetResponse.json() as any;
  const image = fields.find(field => field.kind === "image")!;
  assert.equal((await call("PUT", `${pageUrl}/draft`, { ifRevision: 1, values: { [title.id]: headingEdit, [image.id]: { value: asset.url, alt: "Pixel" } } })).status, 200);
  const rendered = await (await call("GET", `${pageUrl}/preview?pick=1`)).text();
  assert.ok(rendered.includes(`data:image/png;base64,${png}`));
  const assertResponsiveOutput = (output: string) => {
    const sheets = [...output.matchAll(/<style\b[^>]*\bdata-dw-responsive-styles(?:\s*=\s*["'][^"']*["'])?[^>]*>([\s\S]*?)<\/style>/gi)];
    assert.equal(sheets.length, 1, "one generated responsive stylesheet per page");
    assert.match(sheets[0][1], /@media\s*\(\s*max-width\s*:\s*1024px\s*\)/);
    assert.match(sheets[0][1], /@media\s*\(\s*max-width\s*:\s*640px\s*\)/);
    assert.match(sheets[0][1], /\[data-dw-style\s*=/);
    assert.match(sheets[0][1], /font-size\s*:\s*3rem\s*!important/);
    assert.match(sheets[0][1], /font-size\s*:\s*2rem\s*!important/);
    assert.doesNotMatch(output, /tracker\.example|expression\(alert|breakpointInjection/);
    assert.deepEqual(discoverFields(output).fields.find(field => field.id === title.id)?.responsive, responsive);
  };
  assertResponsiveOutput(rendered);
  const viewerPreview = await call("GET", `${pageUrl}/preview?pick=1`, undefined, readCookie);
  assert.equal(viewerPreview.status, 200);
  const viewerHtml = await viewerPreview.text();
  assertResponsiveOutput(viewerHtml);
  assert.match(viewerHtml, /function startEdit\(el\) \{\s*if \(!false\) return;/);
  const downloaded = await call("GET", `${pageUrl}/export`);
  assert.match(downloaded.headers.get("content-disposition")!, /attachment/);
  const exportedHtml = await downloaded.text();
  assert.ok(exportedHtml.includes(`data:image/png;base64,${png}`));
  assertResponsiveOutput(exportedHtml);
  const second = await prisma.site.create({ data: { name: `${mark}-other`, slug: `${mark}-other`, publicUrl: "https://other.example.test" } }); ids.push(second.id);
  assert.equal((await call("GET", `/sites/${second.id}/assets/${asset.id}/content`)).status, 404);
  const config = await (await call("GET", `/sites/${site.id}/config`)).json() as any;
  assert.equal((await call("PUT", `/sites/${site.id}/config`, { ...config, options: { ...config.options, colours: ["#123456"], fonts: ["Georgia"] } })).status, 200);
  assert.deepEqual(((await (await call("GET", `/sites/${site.id}/config`)).json()) as any).options.colours, ["#123456"]);
  assert.ok(((await (await call("GET", `/sites/${site.id}/audit`)).json()) as any[]).some((event: { kind: string }) => event.kind === "ASSET_UPLOAD"));
  const restoredResponsive = { tablet: "display: flex; gap: 1.5rem", mobile: "display: block; gap: 1rem" };
  const version = await prisma.sitePageVersion.create({ data: { pageId: site.pageId, number: 1, html, values: { [container.id]: { style: "display: flex; gap: 3rem", responsive: restoredResponsive } } } });
  assert.equal((await call("POST", `${pageUrl}/versions/${version.id}/restore`, { ifRevision: 2 }, readCookie)).status, 403);
  assert.equal((await call("POST", `${pageUrl}/versions/${version.id}/restore`, { ifRevision: 1 })).status, 409);
  assert.equal((await call("POST", `${pageUrl}/versions/${version.id}/restore`, { ifRevision: 2 })).status, 200);
  const restored = await (await call("GET", pageUrl)).json() as any;
  assert.equal(restored.draft.revision, 3);
  assert.equal(restored.draft.values[container.id].style, "display: flex; gap: 3rem");
  assert.deepEqual(restored.draft.values[container.id].responsive, restoredResponsive);
  assert.deepEqual(((await prisma.sitePage.findUniqueOrThrow({ where: { id: site.pageId } })).draft as any)[container.id].originalResponsive, {});
  assert.equal((await call("DELETE", `${pageUrl}/draft?ifRevision=2`)).status, 409);
  assert.equal((await call("DELETE", `${pageUrl}/draft?ifRevision=3`)).status, 204);
  // A subsequent import of the exported page retains its controls, and {} is a
  // complete removal request rather than "no responsive change supplied".
  await prisma.sitePage.update({ where: { id: site.pageId }, data: { sourceHtml: exportedHtml } });
  const reopened = await (await call("GET", pageUrl)).json() as any;
  const reopenedTitle = reopened.sections.flatMap((section: { fields: unknown[] }) => section.fields).find((field: { id: string }) => field.id === title.id);
  assert.deepEqual(reopenedTitle.responsive, responsive);
  const rollbackReview = await (await call("GET", `${pageUrl}/versions/${version.id}/diff`)).json() as any;
  for (const [device, styles] of Object.entries(responsive)) {
    const label = device === "mobile" ? "phone" : device;
    assert.ok(rollbackReview.differences.some((entry: { label: string; now: string; after: string }) => entry.label.includes(`${label} styling`) && entry.now === styles && entry.after === "(not set)"), `${device} styling removed by rollback must be visible before publishing`);
  }
  assert.ok(rollbackReview.differences.every((entry: { now: string; after: string }) => entry.now !== entry.after), "rollback review shows different before/after values");
  const clearResponsive = await call("PUT", `${pageUrl}/draft`, { ifRevision: 4, values: { [title.id]: { responsive: {} } } });
  assert.equal(clearResponsive.status, 200, await clearResponsive.clone().text());
  const clearedDraft = (await prisma.sitePage.findUniqueOrThrow({ where: { id: site.pageId } })).draft as any;
  assert.deepEqual(clearedDraft[title.id].responsive, {});
  assert.deepEqual(clearedDraft[title.id].originalResponsive, responsive);
  const clearedReview = await (await call("GET", `${pageUrl}/review`)).json() as any;
  assert.equal(clearedReview.publishable, true);
  for (const [device, styles] of Object.entries(responsive)) {
    const label = device === "mobile" ? "phone" : device;
    assert.ok(clearedReview.summary.some((entry: { part: string; label: string; from: string }) => `${entry.part} ${entry.label}`.toLowerCase().includes(label) && entry.from === styles), `${device} removal must appear in the publish review`);
  }
  const clearedExport = await call("GET", `${pageUrl}/export`);
  assert.equal(clearedExport.status, 200);
  const clearedHtml = await clearedExport.text();
  assert.deepEqual(discoverFields(clearedHtml).fields.find(field => field.id === title.id)?.responsive ?? {}, {});
  assert.doesNotMatch(clearedHtml, /data-dw-responsive-styles/);
  assert.equal((await call("POST", `${pageUrl}/structure`, { kind: "duplicate", fieldId: title.id, ifRevision: 5 }, readCookie)).status, 403);
  assert.equal((await call("POST", `${pageUrl}/structure`, { kind: "duplicate", fieldId: title.id, ifRevision: 4 })).status, 409);
  const duplicateResponse = await call("POST", `${pageUrl}/structure`, { kind: "duplicate", fieldId: title.id, ifRevision: 5 });
  assert.equal(duplicateResponse.status, 200, await duplicateResponse.clone().text());
  const copiedId = (await duplicateResponse.json() as any).selectedId;
  const layoutPage = await (await call("GET", pageUrl)).json() as any;
  assert.equal(layoutPage.draft.revision, 6);
  assert.ok(layoutPage.structure.canUndo && layoutPage.structure.changed);
  assert.ok(layoutPage.sections.flatMap((section: { fields: any[] }) => section.fields).some((field: { id: string }) => field.id === copiedId));
  assert.doesNotMatch(JSON.stringify(layoutPage), /"baseHash"|"\$document"|"html":/);
  const cloneEdit = { [copiedId]: { value: "An independent copy" } };
  assert.equal((await call("PUT", `${pageUrl}/draft`, { ifRevision: 6, values: cloneEdit })).status, 409, "older clients cannot silently edit a different layout");
  assert.equal((await call("PUT", `${pageUrl}/draft`, { ifRevision: 6, documentHash: layoutPage.draft.documentHash, values: { $document: {} } })).status, 400);
  assert.equal((await call("PUT", `${pageUrl}/draft`, { ifRevision: 6, documentHash: layoutPage.draft.documentHash, values: cloneEdit })).status, 200);
  const copiedExport = await (await call("GET", `${pageUrl}/export`)).text();
  assert.ok(copiedExport.includes("An independent copy") && copiedExport.includes("Saved heading"));
  const movedCopy = await call("POST", `${pageUrl}/structure`, { kind: "before", fieldId: copiedId, targetId: title.id, ifRevision: 7 });
  assert.equal(movedCopy.status, 200, await movedCopy.clone().text());
  const layoutReview = await (await call("GET", `${pageUrl}/review`)).json() as any;
  assert.ok(layoutReview.publishable && layoutReview.summary.some((entry: { part: string }) => entry.part === "structure"));
  assert.ok(layoutReview.summary.some((entry: { to: string }) => entry.to === "An independent copy"), "layout checkpoint does not hide earlier text changes from review");
  assert.equal((await call("POST", `${pageUrl}/structure`, { kind: "undo", ifRevision: 8 })).status, 200);
  assert.equal((await call("POST", `${pageUrl}/structure`, { kind: "redo", ifRevision: 9 })).status, 200);
  const layoutValues = (await prisma.sitePage.findUniqueOrThrow({ where: { id: site.pageId } })).draft as unknown as Record<string, FieldValue>;
  const layoutVersion = await prisma.sitePageVersion.create({ data: { pageId: site.pageId, number: 2, html: applyValues(exportedHtml, layoutValues).html, values: versionValues(layoutValues) as never } });
  assert.equal((await call("POST", `${pageUrl}/structure`, { kind: "remove", fieldId: copiedId, ifRevision: 10 })).status, 200);
  assert.ok(!(await (await call("GET", `${pageUrl}/export`)).text()).includes("An independent copy"));
  assert.equal((await call("POST", `${pageUrl}/structure`, { kind: "undo", ifRevision: 11 })).status, 200);
  assert.ok((await (await call("GET", `${pageUrl}/export`)).text()).includes("An independent copy"));
  assert.equal((await call("POST", `${pageUrl}/versions/${layoutVersion.id}/restore`, { ifRevision: 12 })).status, 200);
  assert.ok((await (await call("GET", `${pageUrl}/export`)).text()).includes("An independent copy"));
  assert.doesNotMatch(await (await call("GET", `${pageUrl}/versions`)).text(), /"baseHash"|"document":|"undo":|"html":/, "versions expose summaries, never document checkpoints or source HTML");
  const concurrentLayout = await Promise.all(["before", "after"].map(kind => call("POST", `${pageUrl}/structure`, { kind, fieldId: copiedId, targetId: title.id, ifRevision: 13 })));
  assert.deepEqual(concurrentLayout.map(response => response.status).sort(), [200, 409], "only one layout action may claim a revision");
  await prisma.sitePage.update({ where: { id: site.pageId }, data: { sourceHtml: exportedHtml.replace("Saved heading", "Developer heading") } });
  assert.equal((await (await call("GET", `${pageUrl}/review`)).json() as any).publishable, false);
  assert.equal((await (await call("GET", pageUrl)).json() as any).structure.stale, true);
  assert.ok((await (await call("GET", `${pageUrl}/preview?pick=1`)).text()).includes("An independent copy"), "stale draft remains available for inspection");
  assert.equal((await call("GET", `${pageUrl}/export`)).status, 409);
  assert.equal((await call("POST", `${pageUrl}/structure`, { kind: "remove", fieldId: copiedId, ifRevision: 14 })).status, 409);
  assert.equal((await call("DELETE", `${pageUrl}/draft?ifRevision=14`)).status, 204);
  console.log("websiteEditorComplete: stable identity, container and responsive edits, preview policy, real auth, uploads, export, settings, conflict review and restoration checks passed");
} finally {
  await new Promise<void>(resolve => server.close(() => resolve()));
  await prisma.site.deleteMany({ where: { id: { in: ids } } });
  await prisma.user.deleteMany({ where: { id: { in: [owner.id, reader.id] } } });
  await prisma.accessRole.delete({ where: { id: readRole.id } });
  await prisma.$disconnect();
}
