import assert from "node:assert/strict";
import { layerAncestors, visibleWebsiteLayers, websiteLayerNavigation, websiteLayerTabStop, websiteLayerTree } from "../client/src/lib/websiteLayers.js";
const field = (id: string, order: number, parentId?: string) => ({ id, order, parentId, label: id, tag: "div" });
const fields = [field("title", 1, "main"), field("footer", 4, "main"), field("nested", 3, "section"), field("main", 0), field("section", 2, "main")];
const tree = websiteLayerTree(fields);
const ids = (collapsed = new Set<string>(), matches?: Set<string>) => visibleWebsiteLayers(tree.roots, collapsed, matches).map(row => row.node.field.id);
assert.deepEqual(ids(), ["main", "title", "section", "nested", "footer"]);
assert.deepEqual(ids(new Set(["section"])), ["main", "title", "section", "footer"]);
assert.deepEqual(ids(new Set(["main"]), new Set(["nested"])), ["main", "section", "nested"]);
assert.deepEqual(layerAncestors(tree.nodes.get("nested")).map(node => node.field.id), ["main", "section"]);
assert.deepEqual(ids(new Set(), new Set()), []);
const malformed = websiteLayerTree([field("a", 0, "b"), field("b", 1, "a"), field("orphan", 2, "gone")]);
assert.equal(visibleWebsiteLayers(malformed.roots, new Set()).length, 3);

const filteredRows = visibleWebsiteLayers(tree.roots, new Set(["main"]), new Set(["nested"]));
assert.deepEqual(websiteLayerNavigation(filteredRows, 0, "ArrowRight", true), { select: "section" }, "right arrow skips the hidden first child");
assert.deepEqual(websiteLayerNavigation(filteredRows, 1, "ArrowLeft", true), { select: "main" }, "left arrow returns to the visible parent while filtering");
assert.deepEqual(websiteLayerNavigation(filteredRows, 1, "ArrowRight", true), { select: "nested" });
assert.deepEqual(filteredRows.map(row => [row.position, row.siblings]), [[1, 1], [1, 1], [1, 1]], "accessible positions describe displayed siblings");
const parentOnly = visibleWebsiteLayers(tree.roots, new Set(), new Set(["section"]));
assert.equal(parentOnly[1].hasChildren, false, "a match with no displayed children is an accessible leaf");
assert.equal(parentOnly[1].expanded, false);
assert.deepEqual(websiteLayerNavigation(parentOnly, 1, "ArrowRight", true), { select: undefined }, "right arrow never selects a filtered-out child");

const rows = visibleWebsiteLayers(tree.roots, new Set());
assert.deepEqual(websiteLayerNavigation(rows, 2, "ArrowLeft"), { collapse: "section" });
assert.deepEqual(websiteLayerNavigation(rows, 2, "ArrowDown"), { select: "nested" });
assert.deepEqual(websiteLayerNavigation(rows, 2, "ArrowUp"), { select: "title" });
assert.deepEqual(websiteLayerNavigation(rows, 2, "Home"), { select: "main" });
assert.deepEqual(websiteLayerNavigation(rows, 2, "End"), { select: "footer" });
assert.deepEqual(websiteLayerNavigation(rows, 0, "ArrowUp"), { select: undefined });
assert.deepEqual(websiteLayerNavigation(rows, rows.length - 1, "ArrowDown"), { select: undefined });
assert.equal(websiteLayerNavigation(rows, 0, "Enter"), null, "native button activation remains available");
const collapsedRows = visibleWebsiteLayers(tree.roots, new Set(["section"]));
assert.deepEqual(websiteLayerNavigation(collapsedRows, 2, "ArrowRight"), { expand: "section" });
assert.deepEqual(websiteLayerNavigation(collapsedRows, 2, "ArrowLeft"), { select: "main" });
assert.equal(websiteLayerTabStop(collapsedRows, tree.nodes.get("nested")), "section", "hidden selection tabs into its nearest visible ancestor");
assert.equal(websiteLayerTabStop(filteredRows, tree.nodes.get("footer")), "main");
assert.equal(websiteLayerTabStop(rows, tree.nodes.get("nested")), "nested");
assert.equal(websiteLayerTabStop([], tree.nodes.get("nested")), undefined);
console.log("websiteLayers: document order, nested collapse, filtered keyboard navigation, accessible tree positions and selection recovery passed");
