import assert from "node:assert/strict";
import { mkdir, writeFile } from "node:fs/promises";
import { applyValues, buildPreview, buildPublishPlan, discoverFields, sanitizeValue, sanitizeSharedValue } from "../src/services/website/index.js";
import { interactionCss } from "../src/shared/websiteInteraction.js";

const source = '<!doctype html><html><head><title>Test title</title></head><body><section><h1 data-dw-field="hero.title">Make your next idea real</h1><a class="btn-primary" data-dw-field="hero.cta" href="/start">Start today</a></section></body></html>';
const fields = discoverFields(source).fields;
const heading = fields.find(field => field.id === "hero.title")!;
const cta = fields.find(field => field.id === "hero.cta")!;
assert.equal(heading.kind, "text");
const words = 'Make your <span style="color: #ff0000">next idea</span> real';
const edit = sanitizeValue(heading, { value: words });
assert.equal(edit.value, words);
assert.equal(sanitizeSharedValue(heading, { value: words }).value, words);
const saved = applyValues(source, { [heading.id]: edit });
assert.equal(saved.conflicts.length, 0);
assert.ok(saved.html.includes(words));
assert.equal(discoverFields(saved.html).fields.find(field => field.id === heading.id)?.kind, "richtext");
assert.equal(sanitizeValue(fields.find(field => field.tag === "title")!, { value: '<span style="color:red">Title</span>' }).value?.includes("<span"), false);
assert.doesNotMatch(sanitizeValue(heading, { value: 'Words<script>alert(1)</script><span onclick="evil()" style="color:red">here</span>' }).value!, /script|onclick|alert/);
assert.equal(sanitizeValue(cta, { value: 'Start <span style="font-weight:700">today</span>' }).value, 'Start <span style="font-weight:700">today</span>');
const style = 'color: #000000; --dw-hover-color: #ff0000; --dw-focus-background-color: #ffff00; transition: color 150ms';
const styled = sanitizeValue(cta, { style });
assert.match(styled.style!, /--dw-hover-color/);
const plan = buildPublishPlan({ source, values: { [cta.id]: styled, [heading.id]: edit } });
assert.equal(plan.publishable, true);
assert.match(plan.html!, /data-dw-interaction-styles/);
assert.match(plan.html!, /:focus-visible/);
assert.doesNotMatch(plan.html!, /data-dw-state-preview/);
assert.match(interactionCss(), /prefers-reduced-motion/);
const newCta = discoverFields(plan.html!).fields.find(field => field.id === cta.id)!;
const reset = applyValues(plan.html!, { [cta.id]: sanitizeValue(newCta, { style: 'color: #000000' }) });
assert.doesNotMatch(reset.html, /data-dw-interaction-styles/);
assert.equal(applyValues(source, {}).html, source);
assert.doesNotMatch(sanitizeValue(cta, { style: '--dw-hover-color: url(https://evil.test)' }).style ?? "", /url/);
const preview = buildPreview(source, "https://example.com/", fields);
assert.match(preview.html, /data-dw-interaction-preview/);
assert.match(preview.html, /data-dw-state-preview/);
const fragment = buildPreview('<h1>Hello</h1>', "https://example.com/");
assert.match(fragment.html, /data-dw-interaction-preview/);
await mkdir('checks/artifacts', { recursive: true });
await writeFile('checks/artifacts/interaction-published.html', plan.html!);
console.log('websiteInteractions: selection markup, shared sanitization, metadata safety, published hover/focus CSS, resets and fragment previews passed.');
