import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, ApiError } from "../lib/api";
import { Badge, Button, PageHeader } from "../components/ui";

type Purchase = { billingCycle: string; billingState: string; nextBillingAt: string | null; standardRecurringPrice: string | null; billingPriceUpdatedAt: string | null; providerSubscriptionCode: string | null; hasReusableCard: boolean; id: string; status: string; businessName: string; contactName: string; email: string; websiteUrl: string; monthlyPrice: string; setupPrice: string; currency: string; product: { name: string }; invoice: { invoiceNumber: string; status: string; paymentUrl: string | null } | null };
type Booking = { id: string; businessName: string; contactName: string; email: string; phone: string; reason: string; goals: string; requestedAt: string; status: string; adminNotes: string | null };
type Commerce = { purchases: Purchase[]; bookings: Booking[]; paymentAlerts: { id: string; event: string; error: string | null; reviewRequired: boolean }[] };
const PURCHASE_STATES = ["PAYMENT_PENDING", "SETUP_PAID", "SETUP_IN_PROGRESS", "READY", "ACTIVE", "FAILED", "CANCELLED"];
const BOOKING_STATES = ["REQUESTED", "CONFIRMED", "COMPLETED", "CANCELLED"];

export function WebsiteBilling() {
  const qc = useQueryClient();
  const commerce = useQuery({ queryKey: ["website-commerce"], queryFn: () => api.get<Commerce>("/products/website-commerce") });
  const purchase = useMutation({ mutationFn: ({ id, status }: { id: string; status: string }) => api.patch(`/products/website-commerce/purchases/${id}`, { status }), onSuccess: () => qc.invalidateQueries({ queryKey: ["website-commerce"] }) });
  const booking = useMutation({ mutationFn: ({ id, ...data }: { id: string; status?: string; requestedAt?: string; adminNotes?: string }) => api.patch(`/products/website-commerce/bookings/${id}`, data), onSuccess: () => qc.invalidateQueries({ queryKey: ["website-commerce"] }) });
  const manage = useMutation({ mutationFn: (id: string) => api.post<{ url: string }>(`/products/website-commerce/purchases/${id}/manage-billing`, {}), onSuccess: ({ url }) => { window.location.assign(url); } });
  const error = commerce.error || purchase.error || booking.error || manage.error;

  return <div><PageHeader title="Website sales & bookings" subtitle="Setup purchases paid through Paystack and Managed Website consultations." action={<a href="/products/pricing" className="text-sm font-semibold text-blue hover:underline">Adjust plan pricing</a>} />
    {error && <p role="alert" className="mb-4 rounded-xl bg-danger-surface p-3 text-sm text-danger-text">{error instanceof ApiError ? error.message : "The commercial records could not be updated."}</p>}
    {commerce.isLoading && <p className="text-sm text-muted">Loading purchases and bookings…</p>}
    {Boolean(commerce.data?.paymentAlerts.length) && <section className="mb-5 rounded-xl border border-line p-4" aria-label="Payment alerts"><h2 className="font-semibold">Payment events needing review</h2><p className="text-sm text-muted">Review refunds, disputes and expiring cards in Paystack. Failed event processing retries automatically.</p>{commerce.data?.paymentAlerts.map(alert => <p key={alert.id} className="mt-2 text-sm">{alert.event}: {alert.error ?? "Review this event in the Paystack dashboard."} <code>{alert.id.slice(0, 12)}</code></p>)}</section>}
    <section className="mb-8"><h2 className="mb-3 font-display text-xl">Purchases</h2><div className="space-y-3">{commerce.data?.purchases.map(row => <article key={row.id} className="rounded-2xl border border-line bg-white p-5">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{row.businessName} · {row.product.name}</h3><p className="text-xs text-muted">{row.contactName} · {row.email} · <a className="underline" href={row.websiteUrl} target="_blank" rel="noreferrer">website</a></p></div><Badge tone={row.status === "ACTIVE" ? "positive" : row.status === "FAILED" || row.status === "CANCELLED" ? "danger" : "info"}>{row.status.replaceAll("_", " ")}</Badge></div>
      <p className="mt-3 text-sm text-muted">{row.currency} {Number(row.setupPrice).toLocaleString()} setup · {row.billingCycle === "annual" ? `${row.currency} ${Number(row.standardRecurringPrice).toLocaleString()}/year on renewal` : `${row.currency} ${Number(row.billingPriceUpdatedAt ? row.standardRecurringPrice : row.monthlyPrice).toLocaleString()}/month`} · {row.invoice?.invoiceNumber ?? "No invoice"} ({row.invoice?.status ?? "pending"})</p>
      <p className="mt-1 text-sm text-muted">Billing: {row.billingState.replaceAll("_", " ")} · {row.hasReusableCard ? "Reusable card verified" : "No reusable card"}{row.nextBillingAt ? ` · Next billing: ${new Date(row.nextBillingAt).toLocaleDateString()}` : ""}</p>
      <div className="mt-3 flex flex-wrap items-center gap-2"><select disabled={purchase.isPending} aria-label={`Status for ${row.businessName}`} value={row.status} onChange={event => purchase.mutate({ id: row.id, status: event.target.value })} className="h-9 rounded-xl border border-line bg-white px-3 text-sm">{PURCHASE_STATES.map(state => <option key={state}>{state}</option>)}</select>{row.providerSubscriptionCode && <Button size="sm" variant="secondary" disabled={manage.isPending} onClick={() => manage.mutate(row.id)}>Manage card / cancel billing</Button>}{row.invoice?.paymentUrl && row.invoice.status !== "PAID" && <a href={row.invoice.paymentUrl} target="_blank" rel="noreferrer"><Button size="sm" variant="secondary">Open payment</Button></a>}</div>
    </article>)}</div>{commerce.data?.purchases.length === 0 && <p className="text-sm text-muted">No website purchases yet.</p>}</section>
    <section><h2 className="mb-3 font-display text-xl">Managed consultations</h2><div className="space-y-3">{commerce.data?.bookings.map(row => <article key={row.id} className="rounded-2xl border border-line bg-white p-5">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{row.businessName}</h3><p className="text-xs text-muted">{row.contactName} · {row.email} · {row.phone}</p></div><Badge tone={row.status === "CONFIRMED" || row.status === "COMPLETED" ? "positive" : row.status === "CANCELLED" ? "danger" : "warn"}>{row.status}</Badge></div>
      <p className="mt-3 text-sm"><strong>Requested:</strong> {new Date(row.requestedAt).toLocaleString()}</p><p className="mt-1 text-sm text-muted"><strong>Reason:</strong> {row.reason}</p><p className="mt-1 text-sm text-muted"><strong>Goals:</strong> {row.goals}</p>
      <div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="text-xs text-muted">Status<select aria-label={`Booking status for ${row.businessName}`} value={row.status} onChange={event => booking.mutate({ id: row.id, status: event.target.value })} className="mt-1 block h-9 w-full rounded-xl border border-line bg-white px-3 text-sm">{BOOKING_STATES.map(state => <option key={state}>{state}</option>)}</select></label><label className="text-xs text-muted">Consultation time<input type="datetime-local" defaultValue={new Date(row.requestedAt).toISOString().slice(0,16)} onChange={event => booking.mutate({ id: row.id, requestedAt: event.target.value })} className="mt-1 block h-9 w-full rounded-xl border border-line bg-white px-3 text-sm" /></label><label className="text-xs text-muted">Internal notes<input defaultValue={row.adminNotes ?? ""} onBlur={event => booking.mutate({ id: row.id, adminNotes: event.target.value })} className="mt-1 block h-9 w-full rounded-xl border border-line bg-white px-3 text-sm" /></label></div>
    </article>)}</div>{commerce.data?.bookings.length === 0 && <p className="text-sm text-muted">No Managed consultations requested.</p>}</section>
  </div>;
}
