import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
const { chromium } = await import(process.env.PLAYWRIGHT_URL ?? "playwright");
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
const writes = [];
page.on("pageerror", error => errors.push(error.message));
const capabilities = Object.fromEntries(["view", "edit", "review", "publish", "manage", "members", "source"].map(key => [key, true]));
const document = { site: { id: "demo", name: "Demo website", publicUrl: "https://example.com", repo: "demo/site" }, links: [], readFrom: "imported file", page: { id: "one", title: "Home", path: "/", filePath: "index.html", status: "LIVE", url: "https://example.com", lastPublishedAt: null }, sections: [{ id: "hero", label: "Hero", kind: "section", fields: [{ id: "hero.title", kind: "text", tag: "h1", value: "Welcome home", preview: "Welcome home", label: "Main heading", order: 0 }] }], draft: { revision: 0, savedAt: null, savedBy: null, values: {} }, problems: [] };
await page.route("**/api/**", route => {
  const url = new URL(route.request().url());
  if (route.request().method() !== "GET") writes.push(url.pathname);
  if (url.pathname.endsWith("/draft")) {
    const payload=route.request().postDataJSON();
    document.draft={...document.draft, values:payload?.values ?? {}, revision:document.draft.revision+1, savedAt:new Date().toISOString()};
    return route.fulfill({json:{revision:document.draft.revision,problems:[],unknown:[]}});
  }
  if (url.pathname.endsWith("/assistant/preview")) return route.fulfill({json:{html:'<h1>Better together</h1>'}});
  if (url.pathname.endsWith("/assistant")) return route.fulfill({json:{explanation:"A clearer heading",values:{"hero.title":{value:"Better together"}},changes:[{fieldId:"hero.title",label:"Main heading",property:"value",before:"Welcome home",after:"Better together"}],costUsd:0,model:"test",note:null}});
  if (url.pathname.endsWith("/review")) return route.fulfill({json:{revision:document.draft.revision,sourceHash:"fixture",summary:[],problems:[],conflicts:[],missing:[],publishable:true}});
  if (url.pathname.endsWith("/auth/me")) return route.fulfill({ json: { id: "tester", name: "Client", external: true, permissions: [] } });
  if (url.pathname.endsWith("/access")) return route.fulfill({ json: { capabilities } });
  if (url.pathname.endsWith("/design")) return route.fulfill({ json: { options: { colours: [], fonts: [], presets: [], aiEnabled: true } } });
  if (url.pathname.includes("/preview")) return route.fulfill({ contentType: "text/html", body: '<html><body style="margin:0;background:#f4f0e8;font-family:Arial;padding:60px"><h1 data-dw-field="hero.title" style="font-size:64px">Welcome home</h1><p>A quiet space to make your next idea real.</p></body></html>' });
  return route.fulfill({ json: document });
});
try {
  const started=Date.now();
  await page.goto("http://127.0.0.1:5199/builder-harness.html?editor");
  await page.getByRole('button',{name:'Close guide'}).click();
  await page.getByRole('button',{name:'Layers',exact:true}).click();
  await page.getByRole('treeitem',{name:'Welcome home'}).click();
  const heading=page.getByRole('textbox',{name:'Main heading',exact:true});await heading.waitFor();
  console.log(`Editor ready in ${Date.now()-started}ms (local mocked API; not a production benchmark).`);
  assert.equal(await page.locator('.editor-sidebar').evaluate(e=>getComputedStyle(e).width),'340px');
  await page.getByRole('tab',{name:'Style',exact:true}).click();
  await page.getByRole('button',{name:'Typography',exact:true}).waitFor();
  assert.equal(await heading.isVisible(),false);
  await page.getByRole('tab',{name:'Interactions',exact:true}).click();
  await page.getByLabel('hover color',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Active',exact:true}).click();
  await page.getByLabel('active color',{exact:true}).waitFor();
  assert.equal(writes.length,0,'Viewing tabs must not save anything');
  await page.getByRole('tab',{name:'Content',exact:true}).click();
  await heading.fill('Changed heading');await page.keyboard.press('Control+s');
  await page.getByText('Draft saved · 1 unpublished change',{exact:true}).waitFor();
  assert.equal(document.draft.values['hero.title'].value,'Changed heading');
  await page.keyboard.press('Control+z');
  await page.waitForFunction(()=>document.querySelector('[aria-label="Main heading"]').textContent==='Welcome home');
  await page.keyboard.press('Control+Shift+z');
  await page.waitForFunction(()=>document.querySelector('[aria-label="Main heading"]').textContent==='Changed heading');
  await page.keyboard.press('Control+Enter');await page.getByRole('heading',{name:'Review your changes'}).waitFor();
  assert.equal(writes.some(x=>x.endsWith('/publish')),false,'Shortcut opens review, never publishes');
  await page.getByRole('button',{name:'Keep editing'}).click();
  await page.getByText('More',{exact:true}).click();
  page.once('dialog',dialog=>dialog.dismiss());await page.getByRole('button',{name:'Discard',exact:true}).click();
  assert.equal(document.draft.values['hero.title'].value,'Changed heading');
  await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Assistant',exact:true}).click();
  await page.getByLabel('What would you like to change?').fill('Make this heading clearer');
  const before=writes.length;await page.getByRole('button',{name:'Suggest changes',exact:true}).click();
  await page.getByRole('heading',{name:'Review changes',exact:true}).waitFor();
  assert.equal(writes.slice(before).some(x=>x.endsWith('/draft')),false);
  await page.getByRole('button',{name:'Preview selected changes'}).click();
  await page.getByTitle('Proposed page preview').waitFor();
  assert.equal(await page.getByTitle('Proposed page preview').getAttribute('sandbox'),'');
  await page.getByRole('button',{name:'Apply 1 change',exact:true}).click();
  await page.waitForFunction(()=>{const field=document.querySelector('[aria-label="Main heading"]');return !!field&&field.textContent==='Better together';});
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await page.getByText('Draft saved · 1 unpublished change',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Layers',exact:true}).click();
  await page.getByRole('tab',{name:'Style',exact:true}).click();
  await page.screenshot({path:'checks/artifacts/editor-redesign-dark.png',fullPage:true});
  await page.getByText('More',{exact:true}).click();await page.getByRole('button',{name:'Use light editor'}).click();await page.keyboard.press('Escape');
  await page.screenshot({path:'checks/artifacts/editor-redesign-light.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.getByRole('button',{name:'Inspector',exact:true}).click();
  assert.equal(await page.getByRole('complementary',{name:'Element inspector'}).count(),0);
  await page.screenshot({path:'checks/artifacts/editor-redesign-phone.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('Redesign: tabs, themes, mobile, save/undo/redo, publish review shortcut, discard cancellation, AI proposal/preview/approval passed.');
} finally {await browser.close();}
