import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
const { chromium } = await import(process.env.PLAYWRIGHT_URL ?? "playwright");
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } });
const errors = [];
page.on("pageerror", error => errors.push(error.message));
const writes = [];
await page.route("**/builder-fixture.svg", route => route.fulfill({ contentType: "image/svg+xml", body: '<svg xmlns="http://www.w3.org/2000/svg" width="800" height="400"><rect width="800" height="400" fill="#dbc6a5"/><circle cx="580" cy="160" r="110" fill="#3157ff"/><rect x="30" y="220" width="350" height="100" rx="30" fill="#173528"/></svg>' }));
const fixture = id => ({ page: { id, title: `Page ${id}`, path: `/${id}` }, site: { id: "demo" }, sections: [{ fields: [{ id: "cta", kind: "button", tag: "a", label: "Primary CTA", style: "color: white" }] }], draft: { revision: 4, values: { cta: { value: "Keep my content", responsive: { mobile: "padding: 8px" } } } }, problems: [] });
await page.route("**/api/website/**", async route => {
  const url = new URL(route.request().url());
  if (url.pathname.endsWith("/draft")) { writes.push({ url: url.pathname, body: route.request().postDataJSON() }); return route.fulfill({ status: url.pathname.includes("/two/") ? 409 : 200, json: url.pathname.includes("/two/") ? { error: "Another editor changed this draft. Review again." } : { revision: 5, problems: [], unknown: [] } }); }
  if (url.pathname.endsWith("/pages")) return route.fulfill({ json: { pages: [{ id: "one", title: "Page one" }, { id: "two", title: "Page two" }] } });
  return route.fulfill({ json: fixture(url.pathname.split("/").pop()) });
});
try {
  await page.goto("http://127.0.0.1:5199/builder-harness.html");
  await page.getByText("First edit · 1 of 4", { exact: false }).waitFor();
  await page.getByRole("button", { name: "Next step" }).click();
  assert.match(await page.getByRole("region", { name: "First edit walkthrough" }).innerText(), /2 of 4/);
  await page.getByRole("button", { name: "Close guide" }).click();
  assert.equal(await page.locator('[data-section="typography"]').count(), 0);
  await page.getByLabel("Designer controls").check();
  await page.locator('[data-section="typography"]').waitFor();
  await page.getByLabel("Designer controls").uncheck();
  await page.getByLabel("Brand style", { exact: true }).selectOption("primary");
  assert.match(await page.getByTestId("style").innerText(), /background-color: #3157ff/);
  await page.getByText("Crop & focal point", { exact: true }).click();
  await page.getByLabel("Shape", { exact: true }).selectOption("1 / 1");
  await page.getByLabel("Horizontal focal point", { exact: false }).fill("75");
  await page.getByRole("button", { name: "Apply crop to draft" }).click();
  assert.match(await page.getByTestId("style").innerText(), /object-position: 75% 50%/);
  assert.match(await page.getByTestId("style").innerText(), /aspect-ratio: 1 \/ 1/);
  const crop = page.getByRole("button", { name: "Set focal point in Desktop image" });
  const box = await crop.boundingBox();
  assert.ok(Math.abs(box.width - box.height) < 2);
  await page.getByLabel("Publishing state").selectOption("QUEUED");
  assert.match(await page.getByRole("region", { name: "Publishing progress" }).innerText(), /Sending the reviewed changes/);
  await page.getByLabel("Publishing state").selectOption("COMPLETED");
  await page.getByText("Your changes are live.", { exact: true }).waitFor();
  assert.equal(await page.getByRole("link", { name: "Open live website" }).getAttribute("href"), "https://example.com/");
  await page.getByLabel("Publishing state").selectOption("RECONCILIATION_REQUIRED");
  assert.match(await page.getByRole("region", { name: "Publishing progress" }).innerText(), /inspect the recorded commit before retrying/);
  await page.getByLabel("Brand style to apply across pages").selectOption("primary");
  await page.getByRole("button", { name: "Review affected pages" }).click();
  await page.getByRole("link", { name: "Page one" }).waitFor();
  assert.equal(writes.length, 0);
  await page.getByRole("button", { name: "Apply reviewed changes to drafts" }).click();
  await page.getByText("Not applied: Another editor changed", { exact: false }).waitFor();
  assert.equal(writes.length, 2);
  assert.equal(writes[0].body.ifRevision, 4);
  assert.equal(writes[0].body.values.cta.value, "Keep my content");
  assert.equal(writes[0].body.values.cta.responsive.mobile, "padding: 8px");
  assert.equal(await page.getByRole("button", { name: "Apply reviewed changes to drafts" }).isDisabled(), true);
  await mkdir("checks/artifacts", { recursive: true });
  await page.screenshot({ path: "checks/artifacts/builder-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "checks/artifacts/builder-phone.png", fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), "Phone harness should not overflow horizontally");
  assert.deepEqual(errors, []);
  console.log("builderUsability: browser interactions passed, including conflict and preserved content/device drafts; desktop and phone screenshots saved.");
} finally { await browser.close(); }
