#!/usr/bin/env node
/**
 * Writes the search and social metadata into every page of the marketing site.
 *
 * This is a generator rather than thirteen hand-edited heads because that is
 * exactly how the site got into the state it was in: every page had a good
 * description, most had a canonical, three did not, one pointed at
 * `/foundation-build.html` while every link on the site said `/foundation-build`,
 * and not one page had a single Open Graph tag — so every link shared to
 * WhatsApp, LinkedIn or Slack rendered as a bare grey box. Thirteen copies of
 * anything drift. One table does not.
 *
 * It is idempotent: it replaces the block between the two markers, so it can be
 * run after any edit. Nothing outside those markers is touched, and the
 * description and title already in each page are reused rather than rewritten —
 * the copy is the owner's, this only carries it into the tags that need it.
 *
 *   node scripts/build-seo.mjs           # write the tags, the sitemap and robots.txt
 *   node scripts/build-seo.mjs --check   # fail if anything is out of date (CI)
 */

import { readFileSync, writeFileSync } from "node:fs";

const ORIGIN = "https://dakyworld.com";
const SHARE_IMAGE = `${ORIGIN}/assets/brand/og-share.png`;
const SHARE_IMAGE_ALT =
  "Dakyworld — your outsourced IT department. Websites, security, email, cloud, automation and integrations, managed for one monthly fee.";

/**
 * Search-engine ownership verification. Both are the `content` value of the
 * meta tag each console offers — paste them in and re-run; leave one empty and
 * its tag is simply not written.
 *
 * Google Search Console: search.google.com/search-console → add the
 *   `https://dakyworld.com` property → HTML tag → copy the `content` value.
 * Bing Webmaster Tools: bing.com/webmasters → add site → Option 2, meta tag.
 *   (Bing will also import the whole property straight from Search Console,
 *   which is faster and is what to do if Google is already verified.)
 *
 * Verification is what unlocks the part that matters: submitting the sitemap,
 * seeing which queries actually reach the site, and being told about a crawl
 * error rather than discovering it in the traffic.
 */
const VERIFICATION = {
  google: "",
  bing: "",
};

const BEGIN = "<!-- BEGIN SEO — generated by scripts/build-seo.mjs, do not edit by hand -->";
const END = "<!-- END SEO -->";

/**
 * The facts about the company, from server/src/services/dakyworld.ts. Kept
 * here as literals because the website is static HTML with no build step that
 * could import them — if that file changes, change these.
 */
const COMPANY = {
  name: "Dakyworld",
  legalName: "Dakyworld",
  email: "info@dakyworld.com",
  phone: "+233545950611",
  phoneDisplay: "+233 545 950 611",
  locality: "Kumasi",
  region: "Ashanti",
  country: "GH",
  founder: "Dan Kwame Ayipah",
  positioning: "Your outsourced IT department for growing businesses in Ghana and West Africa.",
  currency: "GHS",
  /**
   * Deliberately empty. `sameAs` is how a search engine ties this site to a
   * verified profile, and it is the single strongest signal in the set — but a
   * guessed URL is worse than none: it either 404s or, far worse, points at
   * somebody else's account. Fill these in with the real profile URLs.
   */
  sameAs: [],
};

/**
 * Every page, in the order they appear in the sitemap.
 *
 * `keywords` is short and honest on purpose. Google has ignored the tag since
 * 2009 and a stuffed one is a spam signal to the engines that still read it;
 * what it is worth is a handful of terms per page for Bing, Yandex and the
 * on-site search of anything that indexes this later.
 *
 * `priority` and `changefreq` are hints, not instructions — the crawler decides.
 */
const PAGES = [
  {
    file: "index.html",
    path: "/",
    priority: "1.0",
    changefreq: "weekly",
    keywords: "outsourced IT department Ghana, managed IT services Kumasi, IT support for businesses Ghana, website management, business automation",
    schema: ["organization", "website", "localbusiness"],
  },
  {
    file: "services.html",
    path: "/services",
    priority: "0.9",
    changefreq: "monthly",
    breadcrumb: [["Coverage", "/services"]],
    keywords: "IT services Ghana, website management, cybersecurity, cloud and email management, business automation, systems integration, IT training",
    schema: ["services"],
  },
  {
    file: "pricing.html",
    path: "/pricing",
    priority: "0.9",
    changefreq: "monthly",
    breadcrumb: [["Pricing", "/pricing"]],
    keywords: "IT support pricing Ghana, managed IT retainer cost, website build cost Ghana, IT services pricing",
    schema: ["webpage"],
  },
  {
    file: "monthly-support.html",
    path: "/monthly-support",
    priority: "0.8",
    changefreq: "monthly",
    breadcrumb: [["Pricing", "/pricing"], ["Monthly Support", "/monthly-support"]],
    keywords: "monthly IT support Ghana, managed IT retainer, outsourced IT department, ongoing technology management",
    schema: ["service"],
    service: {
      name: "Monthly Technology Support",
      description:
        "Ongoing outsourced IT: website, security, backups, email and cloud, automation and integrations, managed for a monthly fee.",
    },
  },
  {
    file: "one-time-projects.html",
    path: "/one-time-projects",
    priority: "0.8",
    changefreq: "monthly",
    breadcrumb: [["Pricing", "/pricing"], ["One-Time Projects", "/one-time-projects"]],
    keywords: "one-time digital projects, website design Ghana, brand identity design, technology training, IT consulting Kumasi",
    schema: ["service"],
    service: {
      name: "One-Time Digital Projects",
      description: "Focused projects with a defined outcome: foundation builds, brand identity and design, training and technology advisory.",
    },
  },
  {
    file: "foundation-build.html",
    path: "/foundation-build",
    priority: "0.8",
    changefreq: "monthly",
    breadcrumb: [["Pricing", "/pricing"], ["One-Time Projects", "/one-time-projects"], ["Digital Foundation Build", "/foundation-build"]],
    keywords: "digital foundation build, business website build Ghana, secure business email setup, cloud systems setup, IT foundation",
    schema: ["service"],
    service: {
      name: "Digital Foundation Build",
      description: "A secure, reliable digital foundation: website, business email, cloud systems, security and backups, set up properly once.",
    },
  },
  {
    file: "work.html",
    path: "/work",
    priority: "0.7",
    changefreq: "monthly",
    breadcrumb: [["Work", "/work"]],
    keywords: "IT case studies Ghana, security project, mobile commerce, business automation results",
    schema: ["collection"],
  },
  {
    file: "how-we-work.html",
    path: "/how-we-work",
    priority: "0.7",
    changefreq: "monthly",
    breadcrumb: [["Process", "/how-we-work"]],
    keywords: "how outsourced IT works, IT onboarding process, IT service levels, IT response times",
    schema: ["webpage"],
  },
  {
    file: "about.html",
    path: "/about",
    priority: "0.7",
    changefreq: "monthly",
    breadcrumb: [["About", "/about"]],
    keywords: "about Dakyworld, IT company Kumasi, Dan Kwame Ayipah, IT company Ghana",
    schema: ["about"],
  },
  {
    file: "insights.html",
    path: "/insights",
    priority: "0.6",
    changefreq: "weekly",
    breadcrumb: [["Insights", "/insights"]],
    keywords: "IT insights Ghana, business technology advice, automation and AI for business, cybersecurity guidance",
    schema: ["blog"],
  },
  {
    file: "contact.html",
    path: "/contact",
    priority: "0.8",
    changefreq: "monthly",
    breadcrumb: [["Contact", "/contact"]],
    keywords: "contact Dakyworld, IT support Kumasi, hire IT company Ghana, technology consultation",
    schema: ["contact"],
  },
  {
    file: "privacy.html",
    path: "/privacy",
    priority: "0.3",
    changefreq: "yearly",
    breadcrumb: [["Privacy", "/privacy"]],
    keywords: "privacy policy, data protection Ghana, Act 843",
    schema: ["webpage"],
  },
  {
    file: "terms.html",
    path: "/terms",
    priority: "0.3",
    changefreq: "yearly",
    breadcrumb: [["Terms", "/terms"]],
    keywords: "terms and conditions, service agreement Ghana",
    schema: ["webpage"],
  },
];

// --- reading what each page already says -------------------------------------

const between = (html, open, close) => {
  const start = html.indexOf(open);
  if (start === -1) return null;
  const from = start + open.length;
  const end = html.indexOf(close, from);
  return end === -1 ? null : html.slice(from, end);
};

/** HTML entities appear in the titles (`&reg;`, `&mdash;`); tags carry plain text. */
function decode(text) {
  return text
    .replace(/&reg;/g, "®")
    .replace(/&mdash;/g, "—")
    .replace(/&ndash;/g, "–")
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ");
}

const attr = (value) => value.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

// --- structured data ----------------------------------------------------------

const organisation = {
  "@type": "Organization",
  "@id": `${ORIGIN}/#organization`,
  name: COMPANY.name,
  legalName: COMPANY.legalName,
  url: `${ORIGIN}/`,
  logo: { "@type": "ImageObject", url: `${ORIGIN}/assets/brand/dakyworld-lockup-on-light.png` },
  image: SHARE_IMAGE,
  description: COMPANY.positioning,
  email: COMPANY.email,
  telephone: COMPANY.phone,
  founder: { "@type": "Person", name: COMPANY.founder },
  address: {
    "@type": "PostalAddress",
    addressLocality: COMPANY.locality,
    addressRegion: COMPANY.region,
    addressCountry: COMPANY.country,
  },
  ...(COMPANY.sameAs.length ? { sameAs: COMPANY.sameAs } : {}),
};

/**
 * `ProfessionalService` rather than the bare `LocalBusiness`: it is the
 * narrower type and search engines prefer the narrowest that fits. No opening
 * hours and no geo coordinates, because inventing either would be a false
 * statement about a real business — see the note in the README on what still
 * has to come from the owner.
 */
const localBusiness = {
  "@type": "ProfessionalService",
  "@id": `${ORIGIN}/#localbusiness`,
  name: COMPANY.name,
  url: `${ORIGIN}/`,
  image: SHARE_IMAGE,
  description: COMPANY.positioning,
  email: COMPANY.email,
  telephone: COMPANY.phone,
  priceRange: "GHS 5,000 – GHS 35,000+",
  currenciesAccepted: COMPANY.currency,
  address: {
    "@type": "PostalAddress",
    addressLocality: COMPANY.locality,
    addressRegion: COMPANY.region,
    addressCountry: COMPANY.country,
  },
  areaServed: [
    { "@type": "Country", name: "Ghana" },
    { "@type": "Place", name: "West Africa" },
  ],
  parentOrganization: { "@id": `${ORIGIN}/#organization` },
};

const website = {
  "@type": "WebSite",
  "@id": `${ORIGIN}/#website`,
  url: `${ORIGIN}/`,
  name: COMPANY.name,
  description: COMPANY.positioning,
  inLanguage: "en-GB",
  publisher: { "@id": `${ORIGIN}/#organization` },
};

/** The seven lines the site itself lists under Coverage. */
const SERVICE_CATALOGUE = [
  ["Website design and management", "Building, hosting and maintaining the website a business runs on."],
  ["Security and backups", "Protecting systems and data, and keeping a recoverable copy of both."],
  ["Email and cloud workspace", "Business email, file storage and the tools a team works in."],
  ["Automation and AI", "Removing manual admin from the work that repeats."],
  ["Systems integration", "Making the tools a business already pays for talk to each other."],
  ["Branding and design", "Identity and the material that carries it."],
  ["Training and technology advisory", "Teaching the team, and advising on what to buy and what to skip."],
];

function schemaFor(page, title, description) {
  const url = `${ORIGIN}${page.path}`;
  const graph = [];

  for (const kind of page.schema ?? []) {
    if (kind === "organization") graph.push(organisation);
    if (kind === "website") graph.push(website);
    if (kind === "localbusiness") graph.push(localBusiness);
    if (kind === "services") {
      graph.push({
        "@type": "OfferCatalog",
        "@id": `${url}#catalogue`,
        name: "What Dakyworld covers",
        url,
        provider: { "@id": `${ORIGIN}/#organization` },
        itemListElement: SERVICE_CATALOGUE.map(([name, text], index) => ({
          "@type": "Offer",
          position: index + 1,
          itemOffered: { "@type": "Service", name, description: text, provider: { "@id": `${ORIGIN}/#organization` } },
        })),
      });
    }
    if (kind === "service" && page.service) {
      graph.push({
        "@type": "Service",
        "@id": `${url}#service`,
        name: page.service.name,
        description: page.service.description,
        url,
        serviceType: "Information technology services",
        provider: { "@id": `${ORIGIN}/#organization` },
        areaServed: [
          { "@type": "Country", name: "Ghana" },
          { "@type": "Place", name: "West Africa" },
        ],
      });
    }
    if (kind === "blog") {
      graph.push({ "@type": "Blog", "@id": `${url}#blog`, url, name: title, description, publisher: { "@id": `${ORIGIN}/#organization` }, inLanguage: "en-GB" });
    }
    if (kind === "contact") {
      graph.push({ "@type": "ContactPage", "@id": `${url}#page`, url, name: title, description, isPartOf: { "@id": `${ORIGIN}/#website` } });
    }
    if (kind === "about") {
      graph.push({ "@type": "AboutPage", "@id": `${url}#page`, url, name: title, description, isPartOf: { "@id": `${ORIGIN}/#website` }, about: { "@id": `${ORIGIN}/#organization` } });
    }
    if (kind === "collection") {
      graph.push({ "@type": "CollectionPage", "@id": `${url}#page`, url, name: title, description, isPartOf: { "@id": `${ORIGIN}/#website` } });
    }
    if (kind === "webpage") {
      graph.push({ "@type": "WebPage", "@id": `${url}#page`, url, name: title, description, isPartOf: { "@id": `${ORIGIN}/#website` } });
    }
  }

  if (page.breadcrumb?.length) {
    graph.push({
      "@type": "BreadcrumbList",
      "@id": `${url}#breadcrumb`,
      itemListElement: [["Home", "/"], ...page.breadcrumb].map(([name, href], index) => ({
        "@type": "ListItem",
        position: index + 1,
        name,
        item: `${ORIGIN}${href === "/" ? "/" : href}`,
      })),
    });
  }

  return { "@context": "https://schema.org", "@graph": graph };
}

// --- the block that goes into each head ---------------------------------------

function headBlock(page, title, description) {
  const url = `${ORIGIN}${page.path}`;
  const json = JSON.stringify(schemaFor(page, title, description), null, 2);

  return [
    BEGIN,
    `<link rel="canonical" href="${url}">`,
    `<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">`,
    `<meta name="keywords" content="${attr(page.keywords)}">`,
    `<meta name="author" content="${COMPANY.name}">`,
    `<meta name="geo.region" content="GH-AH">`,
    `<meta name="geo.placename" content="${COMPANY.locality}">`,
    ...(VERIFICATION.google ? [`<meta name="google-site-verification" content="${attr(VERIFICATION.google)}">`] : []),
    ...(VERIFICATION.bing ? [`<meta name="msvalidate.01" content="${attr(VERIFICATION.bing)}">`] : []),
    ``,
    `<meta property="og:type" content="website">`,
    `<meta property="og:site_name" content="${COMPANY.name}">`,
    `<meta property="og:locale" content="en_GB">`,
    `<meta property="og:url" content="${url}">`,
    `<meta property="og:title" content="${attr(title)}">`,
    `<meta property="og:description" content="${attr(description)}">`,
    `<meta property="og:image" content="${SHARE_IMAGE}">`,
    `<meta property="og:image:width" content="1200">`,
    `<meta property="og:image:height" content="630">`,
    `<meta property="og:image:type" content="image/png">`,
    `<meta property="og:image:alt" content="${attr(SHARE_IMAGE_ALT)}">`,
    ``,
    `<meta name="twitter:card" content="summary_large_image">`,
    `<meta name="twitter:title" content="${attr(title)}">`,
    `<meta name="twitter:description" content="${attr(description)}">`,
    `<meta name="twitter:image" content="${SHARE_IMAGE}">`,
    `<meta name="twitter:image:alt" content="${attr(SHARE_IMAGE_ALT)}">`,
    ``,
    `<script type="application/ld+json">`,
    json,
    `</script>`,
    ``,
    `<!-- Does nothing until the GA4 Measurement ID is filled in at the top of that file. -->`,
    `<script src="/assets/analytics.js" defer></script>`,
    END,
  ].join("\n");
}

/** Everything this generator owns is inside the markers, plus the old stray canonical it replaces. */
function applyTo(html, block) {
  let next = html;

  const begin = next.indexOf(BEGIN);
  if (begin !== -1) {
    const end = next.indexOf(END, begin);
    next = next.slice(0, begin) + block + next.slice(end + END.length);
    return next;
  }

  // First run: drop any hand-written canonical, then insert after the title.
  next = next.replace(/^[ \t]*<link rel="canonical"[^>]*>\r?\n/m, "");
  const titleEnd = next.indexOf("</title>");
  if (titleEnd === -1) throw new Error("no <title> to anchor to");
  const at = titleEnd + "</title>".length;
  return `${next.slice(0, at)}\n${block}${next.slice(at)}`;
}

// --- run ----------------------------------------------------------------------

const check = process.argv.includes("--check");
const stale = [];

for (const page of PAGES) {
  const html = readFileSync(page.file, "utf8");
  const rawTitle = between(html, "<title>", "</title>");
  const description = between(html, 'name="description" content="', '"');
  if (!rawTitle || !description) throw new Error(`${page.file}: missing a title or a description to build from`);

  const next = applyTo(html, headBlock(page, decode(rawTitle.trim()), decode(description.trim())));
  if (next === html) continue;
  if (check) stale.push(page.file);
  else writeFileSync(page.file, next);
}

// robots.txt — one Sitemap line is what actually gets the sitemap found; the
// rest is politeness. Nothing is disallowed because nothing here is private:
// the whole site is thirteen pages meant to be read.
const robots = `# ${ORIGIN}
User-agent: *
Allow: /

# Superseded homepage explorations. Served so old links do not break, but they
# are duplicate copy and must never compete with the real pages in an index.
Disallow: /website-drafts/

Sitemap: ${ORIGIN}/sitemap.xml
`;

const today = new Date().toISOString().slice(0, 10);
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${PAGES.map(
  (page) => `  <url>
    <loc>${ORIGIN}${page.path}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${page.changefreq}</changefreq>
    <priority>${page.priority}</priority>
  </url>`,
).join("\n")}
</urlset>
`;

for (const [file, content] of [
  ["robots.txt", robots],
  ["sitemap.xml", sitemap],
]) {
  const current = (() => {
    try {
      return readFileSync(file, "utf8");
    } catch {
      return null;
    }
  })();
  // lastmod changes daily; only the shape of the file matters for --check.
  const same = current !== null && current.replace(/<lastmod>[^<]*<\/lastmod>/g, "") === content.replace(/<lastmod>[^<]*<\/lastmod>/g, "");
  if (same) continue;
  if (check) stale.push(file);
  else writeFileSync(file, content);
}

if (check) {
  if (stale.length) {
    console.error(`Out of date — run "node scripts/build-seo.mjs":\n  ${stale.join("\n  ")}`);
    process.exit(1);
  }
  console.log("SEO metadata is up to date.");
} else {
  console.log(`Wrote SEO metadata into ${PAGES.length} pages, plus robots.txt and sitemap.xml.`);
}
