#!/usr/bin/env node
/**
 * Writes the search and social metadata into every page of the marketing site.
 *
 * This is a generator rather than thirteen hand-edited heads because that is
 * exactly how the site got into the state it was in: every page had a good
 * description, most had a canonical, three did not, one pointed at
 * `/foundation-build.html` while every link on the site said `/foundation-build`,
 * and not one page had a single Open Graph tag — so every link shared to
 * WhatsApp, LinkedIn or Slack rendered as a bare grey box. Thirteen copies of
 * anything drift. One table does not.
 *
 * It is idempotent: it replaces the block between the two markers, so it can be
 * run after any edit. Nothing outside those markers is touched, and the
 * description and title already in each page are reused rather than rewritten —
 * the copy is the owner's, this only carries it into the tags that need it.
 *
 *   node scripts/build-seo.mjs           # write the tags, the sitemap and robots.txt
 *   node scripts/build-seo.mjs --check   # fail if anything is out of date (CI)
 */

import { readFileSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { articles } from "./build-articles.mjs";

const ORIGIN = "https://dakyx.com";
const SHARE_IMAGE = `${ORIGIN}/assets/brand/og-share.png`;
const SHARE_IMAGE_ALT =
  "DakyXTech — your external technology team. Websites, custom software, automation and AI, systems integration, consulting and training.";

/**
 * Search-engine ownership verification. Both are the `content` value of the
 * meta tag each console offers — paste them in and re-run; leave one empty and
 * its tag is simply not written.
 *
 * Google Search Console: search.google.com/search-console → add the
 *   `https://dakyx.com` property → HTML tag → copy the `content` value.
 * Bing Webmaster Tools: bing.com/webmasters → add site → Option 2, meta tag.
 *   (Bing will also import the whole property straight from Search Console,
 *   which is faster and is what to do if Google is already verified.)
 *
 * Verification is what unlocks the part that matters: submitting the sitemap,
 * seeing which queries actually reach the site, and being told about a crawl
 * error rather than discovering it in the traffic.
 */
const VERIFICATION = {
  google: "__SS79S0Rgb9gDq67YsklFapwqzHdJRuKL0U4Hw6szY",
  bing: "228757327614DFC34BFD44607745AB46",
  /* Yandex Webmaster: webmaster.yandex.com → Add site → Meta tag. */
  yandex: "",
  /* Naver Search Advisor: searchadvisor.naver.com → HTML tag. */
  naver: "",
};

/**
 * IndexNow — the push protocol Bing, Yandex, Seznam, Naver and Yep share, and
 * the index Copilot and ChatGPT search draw on for freshness. No account is
 * needed: the key file at the site root proves ownership, and
 * scripts/indexnow.mjs submits every sitemap URL after a deploy. The key is
 * public by design; it only proves that whoever pings controls this site.
 */
export const INDEXNOW_KEY = "6f1d2c8a94b34e0f8a7c5b1e3d9f2a60";

/** The search-and-answer crawlers robots.txt welcomes by name. */
const AI_CRAWLERS = [
  "OAI-SearchBot",
  "ChatGPT-User",
  "GPTBot",
  "Claude-SearchBot",
  "Claude-User",
  "ClaudeBot",
  "PerplexityBot",
  "Perplexity-User",
  "Google-Extended",
  "Applebot-Extended",
  "Bingbot",
  "DuckAssistBot",
  "MistralAI-User",
  "Meta-ExternalAgent",
];

const BEGIN = "<!-- BEGIN SEO — generated by scripts/build-seo.mjs, do not edit by hand -->";
const END = "<!-- END SEO -->";

/**
 * The facts about the company, from server/src/services/dakyworld.ts. Kept
 * here as literals because the website is static HTML with no build step that
 * could import them — if that file changes, change these.
 */
const COMPANY = {
  name: "DakyXTech",
  legalName: "DakyXTech",
  email: "info@dakyx.com",
  phone: "+233545950611",
  phoneDisplay: "+233 545 950 611",
  locality: "Kumasi",
  region: "Ashanti",
  country: "GH",
  founder: "Dan Kwame Ayipah",
  positioning:
    "Your external technology team. DakyXTech builds, manages and continuously improves the websites, custom software, automations, AI workflows and integrations businesses depend on, through clear monthly plans.",
  slogan: "Your Technology Team. Without the Overhead.",
  currency: "GHS",
  /**
   * Deliberately empty. `sameAs` is how a search engine ties this site to a
   * verified profile, and it is the single strongest signal in the set — but a
   * guessed URL is worse than none: it either 404s or, far worse, points at
   * somebody else's account. Fill these in with the real profile URLs.
   */
  sameAs: [
    "https://www.linkedin.com/company/dakyx/",
    "https://x.com/DakyXTech",
    "https://www.tiktok.com/@dakyxtech",
    "https://www.instagram.com/dakyxtech/",
    "https://www.threads.com/@dakyxtech",
  ],
};

/**
 * The nine posts under /blog, described by the same front matter that builds
 * them — so an article's date, section and reading time are stated once, in
 * the .md file, and reach the card, the page and the `BlogPosting` from there.
 * `keywords` is the section, which is as much as is honest for a post.
 */
const ARTICLES = articles.map((article) => ({
  file: `blog/${article.slug}.html`,
  path: article.path,
  priority: "0.5",
  changefreq: "yearly",
  breadcrumb: [["Insights", "/insights"], [article.meta.title, article.path]],
  keywords: article.meta.section.toLowerCase(),
  schema: ["article"],
  article: {
    published: article.meta.published,
    section: article.meta.section,
    minutes: article.minutes,
    words: article.words,
  },
}));

/**
 * Every page, in the order they appear in the sitemap.
 *
 * `keywords` is short and honest on purpose. Google has ignored the tag since
 * 2009 and a stuffed one is a spam signal to the engines that still read it;
 * what it is worth is a handful of terms per page for Bing, Yandex and the
 * on-site search of anything that indexes this later.
 *
 * `priority` and `changefreq` are hints, not instructions — the crawler decides.
 */
export const PAGES = [
  {
    file: "index.html",
    path: "/",
    priority: "1.0",
    changefreq: "weekly",
    keywords: "outsourced technology team, external development team, managed website and software, business automation and AI, systems integration, technology partner",
    schema: ["organization", "website", "localbusiness"],
  },
  {
    file: "services.html",
    path: "/services",
    priority: "0.9",
    changefreq: "monthly",
    breadcrumb: [["Services", "/services"]],
    keywords: "website development, custom software development, business automation, AI workflows, systems integration, API integration, technology consulting, AI training",
    schema: ["services"],
  },
  {
    file: "pricing.html",
    path: "/pricing",
    priority: "0.9",
    changefreq: "monthly",
    breadcrumb: [["Pricing", "/pricing"]],
    keywords: "monthly technology plans, technology subscription pricing, development retainer pricing, website and software management plans, enterprise technology partnership",
    schema: ["service"],
    service: {
      name: "Monthly technology plans",
      description:
        "Fixed-price monthly plans in which DakyXTech builds, manages and improves a client's websites, software, automations, AI workflows and integrations within a defined monthly allowance.",
    },
  },
  {
    file: "checkout.html",
    path: "/checkout",
    priority: "0.1",
    changefreq: "yearly",
    keywords: "",
    schema: [],
    // Somebody arriving here from a search result has skipped the page that
    // explains what they would be buying, and a checkout ranking against
    // /website-builder competes with it for the same query.
    noindex: true,
    noindexReason: "The checkout. It is a step in a purchase, not a page to arrive at from a search.",
  },
  {
    file: "products.html",
    path: "/products",
    priority: "0.8",
    changefreq: "monthly",
    breadcrumb: [["Products", "/products"]],
    keywords: "DakyXTech products, business software Ghana, digital tools for business, DakyXTech Website Builder",
    schema: ["collection", "software"],
  },
  {
    file: "website-builder.html",
    path: "/website-builder",
    priority: "0.8",
    changefreq: "monthly",
    breadcrumb: [["Products", "/products"], ["Website Builder", "/website-builder"]],
    keywords: "website builder, edit website without code, publish website changes, client website editor Ghana",
    schema: ["webpage", "software"],
  },
  {
    file: "website-builder-setup.html",
    path: "/website-builder-setup",
    priority: "0.6",
    changefreq: "monthly",
    breadcrumb: [["Products", "/products"], ["Website Builder", "/website-builder"], ["Setup guide", "/website-builder-setup"]],
    keywords: "website builder setup guide, connect GitHub repository, publish website changes, DakyXTech documentation",
    schema: ["webpage"],
  },
  {
    file: "work.html",
    path: "/work",
    priority: "0.7",
    changefreq: "monthly",
    breadcrumb: [["Work", "/work"]],
    keywords: "digital systems case studies Ghana, customer journey improvement, mobile commerce, business automation results",
    schema: ["collection"],
  },
  {
    file: "how-we-work.html",
    path: "/how-we-work",
    priority: "0.7",
    changefreq: "monthly",
    breadcrumb: [["How We Work", "/how-we-work"]],
    keywords: "how DakyXTech works, digital project process, written scope and proposal, monthly partnership process",
    schema: ["webpage"],
  },
  {
    file: "about.html",
    path: "/about",
    priority: "0.7",
    changefreq: "monthly",
    breadcrumb: [["About", "/about"]],
    keywords: "about DakyXTech, external technology team, Dan Kwame Ayipah, technology company Kumasi Ghana",
    schema: ["about"],
  },
  {
    file: "insights.html",
    path: "/insights",
    priority: "0.6",
    changefreq: "weekly",
    breadcrumb: [["Insights", "/insights"]],
    keywords: "business technology insights, automation advice, AI adoption, website and software guidance",
    schema: ["blog"],
  },
  {
    file: "contact.html",
    path: "/contact",
    priority: "0.8",
    changefreq: "monthly",
    breadcrumb: [["Contact", "/contact"]],
    keywords: "contact DakyXTech, technology consultation, hire an external development team, website and software enquiry",
    schema: ["contact"],
  },
  {
    file: "privacy.html",
    path: "/privacy",
    priority: "0.3",
    changefreq: "yearly",
    breadcrumb: [["Privacy", "/privacy"]],
    keywords: "privacy policy, cookie policy, GDPR, data protection Ghana, Act 843, data subject rights",
    schema: ["webpage"],
  },
  {
    file: "terms.html",
    path: "/terms",
    priority: "0.3",
    changefreq: "yearly",
    breadcrumb: [["Terms", "/terms"]],
    keywords: "terms and conditions, service agreement Ghana",
    schema: ["webpage"],
  },
  ...ARTICLES,
];

// --- reading what each page already says -------------------------------------

const between = (html, open, close) => {
  const start = html.indexOf(open);
  if (start === -1) return null;
  const from = start + open.length;
  const end = html.indexOf(close, from);
  return end === -1 ? null : html.slice(from, end);
};

/** HTML entities appear in the titles (`&reg;`, `&mdash;`); tags carry plain text. */
function decode(text) {
  return text
    .replace(/&reg;/g, "®")
    .replace(/&mdash;/g, "—")
    .replace(/&ndash;/g, "–")
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ");
}

const attr = (value) => value.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/**
 * The questions and answers a page already shows, read out of its own markup.
 *
 * Every FAQ on this site is the same shape — `<details><summary>question<span>+
 * </span></summary><p>answer</p></details>` — so the schema can be built from
 * the copy instead of being typed a second time into this file. That is not
 * only tidier: a hand-kept copy is how the FAQ blocks came to live *inside* the
 * do-not-edit markers in the first place, where the next run of this script
 * would have deleted them. Read it from the page and the two cannot disagree.
 *
 * A page with no `<details>` gets no FAQPage, which is the correct outcome for
 * every page that has no questions on it.
 */
function readFaq(html) {
  const out = [];
  for (const block of html.matchAll(/<details\b[^>]*>\s*<summary>([\s\S]*?)<\/summary>([\s\S]*?)<\/details>/g)) {
    /* The `<span>+</span>` is the open/close chevron, not part of the question —
       strip the span and its contents before the tags, or every question in the
       schema ends in a plus sign. */
    const question = decode(
      block[1].replace(/<span\b[^>]*>[\s\S]*?<\/span>/g, "").replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim(),
    );
    const answer = decode(block[2].replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim());
    if (question && answer) out.push({ question, answer });
  }
  return out;
}

// --- structured data ----------------------------------------------------------

const organisation = {
  "@type": "Organization",
  "@id": `${ORIGIN}/#organization`,
  name: COMPANY.name,
  legalName: COMPANY.legalName,
  url: `${ORIGIN}/`,
  logo: { "@type": "ImageObject", url: `${ORIGIN}/assets/brand/dakyworld-lockup-on-light.png` },
  image: SHARE_IMAGE,
  description: COMPANY.positioning,
  email: COMPANY.email,
  telephone: COMPANY.phone,
  slogan: COMPANY.slogan,
  founder: { "@type": "Person", name: COMPANY.founder },
  contactPoint: {
    "@type": "ContactPoint",
    contactType: "sales",
    email: COMPANY.email,
    telephone: COMPANY.phone,
    availableLanguage: ["English"],
  },
  knowsAbout: [
    "Website development",
    "Custom software development",
    "Business process automation",
    "Artificial intelligence workflows",
    "Systems integration",
    "Technology consulting",
    "AI training",
  ],
  address: {
    "@type": "PostalAddress",
    addressLocality: COMPANY.locality,
    addressRegion: COMPANY.region,
    addressCountry: COMPANY.country,
  },
  ...(COMPANY.sameAs.length ? { sameAs: COMPANY.sameAs } : {}),
};

/**
 * `ProfessionalService` rather than the bare `LocalBusiness`: it is the
 * narrower type and search engines prefer the narrowest that fits. No opening
 * hours and no geo coordinates, because inventing either would be a false
 * statement about a real business — see the note in the README on what still
 * has to come from the owner.
 */
const localBusiness = {
  "@type": "ProfessionalService",
  "@id": `${ORIGIN}/#localbusiness`,
  name: COMPANY.name,
  url: `${ORIGIN}/`,
  image: SHARE_IMAGE,
  description: COMPANY.positioning,
  email: COMPANY.email,
  telephone: COMPANY.phone,
  priceRange: "GHS 3,150 – GHS 28,000 per month",
  currenciesAccepted: COMPANY.currency,
  address: {
    "@type": "PostalAddress",
    addressLocality: COMPANY.locality,
    addressRegion: COMPANY.region,
    addressCountry: COMPANY.country,
  },
  parentOrganization: { "@id": `${ORIGIN}/#organization` },
};

const website = {
  "@type": "WebSite",
  "@id": `${ORIGIN}/#website`,
  url: `${ORIGIN}/`,
  name: COMPANY.name,
  description: COMPANY.positioning,
  inLanguage: "en-GB",
  publisher: { "@id": `${ORIGIN}/#organization` },
};

/**
 * The Website Builder, as a product a search engine can quote.
 *
 * The price here is the published one, and it is also the fallback: at runtime
 * assets/pricing.js replaces both the visible number and the `price` on this
 * offer from `os.dakyx.com/api/public/products`, so the office moves a
 * price in one place. What this constant must never become is a *different*
 * number from the one the OS holds — a crawler reads the static value, and a
 * price in a search result that the checkout does not charge is the one kind
 * of drift that costs more than it saves. If the OS number moves permanently,
 * move this one too and re-run.
 */
const WEBSITE_BUILDER = {
  name: "DakyXTech Website Builder",
  path: "/website-builder",
  description:
    "Edit your own website in place and publish when you are ready. Included at no extra cost on any DakyXTech monthly partnership.",
  price: "36",
  setup: null,
};

/** The five service families the site lists under Services, with their anchors. */
const SERVICE_CATALOGUE = [
  ["Websites and digital platforms", "Business websites, redesigns, e-commerce, landing pages, customer portals, web apps, performance and maintenance.", "#websites"],
  ["Software and business systems", "Custom operational software, CRMs, internal dashboards, client portals and reporting.", "#software"],
  ["Business automation and AI", "Workflow automation, AI assistants for defined business tasks, follow-ups, notifications and scheduled reports.", "#automation"],
  ["Systems integration", "Connecting websites, forms, payments, CRM, email, calendars, WhatsApp, inventory and external APIs.", "#integration"],
  ["Technology consulting and training", "Digital systems reviews, technology roadmaps, AI adoption coaching and training on the systems we build.", "#consulting"],
];

/**
 * The three standard plans as published on /pricing — change both together.
 * `intro` is each of a new customer's first three months; Enterprise is quoted
 * individually, so it carries no price at all.
 */
const PLANS = [
  { name: "Foundation", price: 4500, intro: 3150 },
  { name: "Growth", price: 12000, intro: 8400 },
  { name: "Transformation", price: 28000, intro: 19600 },
];

function schemaFor(page, title, description, faq) {
  const url = `${ORIGIN}${page.path}`;
  const graph = [];

  for (const kind of page.schema ?? []) {
    if (kind === "organization") graph.push(organisation);
    if (kind === "website") graph.push(website);
    if (kind === "localbusiness") graph.push(localBusiness);
    if (kind === "services") {
      graph.push({
        "@type": "OfferCatalog",
        "@id": `${url}#catalogue`,
        name: "What DakyXTech does",
        url,
        provider: { "@id": `${ORIGIN}/#organization` },
        itemListElement: SERVICE_CATALOGUE.map(([name, text, anchor], index) => ({
          "@type": "Offer",
          position: index + 1,
          itemOffered: { "@type": "Service", "@id": `${url}${anchor}`, name, description: text, url: `${url}${anchor}`, provider: { "@id": `${ORIGIN}/#organization` } },
        })),
      });
    }
    if (kind === "service" && page.service) {
      graph.push({
        "@type": "Service",
        "@id": `${url}#service`,
        name: page.service.name,
        description: page.service.description,
        url,
        serviceType: "Managed technology services",
        provider: { "@id": `${ORIGIN}/#organization` },
        offers: [
          ...PLANS.map((plan) => ({
            "@type": "Offer",
            name: plan.name,
            url: `${url}#plans`,
            priceCurrency: COMPANY.currency,
            price: String(plan.price),
            priceSpecification: [
              {
                "@type": "UnitPriceSpecification",
                price: String(plan.intro),
                priceCurrency: COMPANY.currency,
                unitCode: "MON",
                billingDuration: 3,
                description: "Introductory price for a new customer, each of the first three months",
              },
              {
                "@type": "UnitPriceSpecification",
                price: String(plan.price),
                priceCurrency: COMPANY.currency,
                unitCode: "MON",
                description: "Regular monthly price from month four",
              },
            ],
          })),
          { "@type": "Offer", name: "Enterprise Technology Partnership", url: `${url}#enterprise`, description: "Custom quote after an assessment." },
        ],
      });
    }
    if (kind === "blog") {
      graph.push({ "@type": "Blog", "@id": `${url}#blog`, url, name: title, description, publisher: { "@id": `${ORIGIN}/#organization` }, inLanguage: "en-GB" });
    }
    if (kind === "contact") {
      graph.push({ "@type": "ContactPage", "@id": `${url}#page`, url, name: title, description, isPartOf: { "@id": `${ORIGIN}/#website` } });
    }
    if (kind === "about") {
      graph.push({ "@type": "AboutPage", "@id": `${url}#page`, url, name: title, description, isPartOf: { "@id": `${ORIGIN}/#website` }, about: { "@id": `${ORIGIN}/#organization` } });
    }
    if (kind === "collection") {
      graph.push({ "@type": "CollectionPage", "@id": `${url}#page`, url, name: title, description, isPartOf: { "@id": `${ORIGIN}/#website` } });
    }
    if (kind === "webpage") {
      graph.push({ "@type": "WebPage", "@id": `${url}#page`, url, name: title, description, isPartOf: { "@id": `${ORIGIN}/#website` } });
    }
    if (kind === "software") {
      graph.push({
        "@type": "SoftwareApplication",
        "@id": `${ORIGIN}${WEBSITE_BUILDER.path}#software`,
        name: WEBSITE_BUILDER.name,
        applicationCategory: "BusinessApplication",
        operatingSystem: "Web browser",
        url: `${ORIGIN}${WEBSITE_BUILDER.path}`,
        provider: { "@id": `${ORIGIN}/#organization` },
        description: WEBSITE_BUILDER.description,
        offers: {
          "@type": "Offer",
          "@id": `${ORIGIN}${WEBSITE_BUILDER.path}#offer`,
          priceCurrency: COMPANY.currency,
          price: WEBSITE_BUILDER.price,
          availability: "https://schema.org/InStock",
          url: `${ORIGIN}${WEBSITE_BUILDER.path}`,
        },
      });
    }
    if (kind === "article" && page.article) {
      graph.push({
        "@type": "BlogPosting",
        "@id": `${url}#article`,
        headline: page.article.headline ?? title,
        description,
        url,
        mainEntityOfPage: { "@type": "WebPage", "@id": `${url}#page` },
        datePublished: page.article.published,
        dateModified: page.article.published,
        articleSection: page.article.section,
        wordCount: page.article.words,
        timeRequired: `PT${page.article.minutes}M`,
        inLanguage: "en-GB",
        image: SHARE_IMAGE,
        isPartOf: { "@id": `${ORIGIN}/insights#blog` },
        author: { "@id": `${ORIGIN}/#organization` },
        publisher: { "@id": `${ORIGIN}/#organization` },
      });
    }
  }

  if (page.breadcrumb?.length) {
    graph.push({
      "@type": "BreadcrumbList",
      "@id": `${url}#breadcrumb`,
      itemListElement: [["Home", "/"], ...page.breadcrumb].map(([name, href], index) => ({
        "@type": "ListItem",
        position: index + 1,
        name,
        item: `${ORIGIN}${href === "/" ? "/" : href}`,
      })),
    });
  }

  /* Read from the page's own `<details>`, so the questions on screen and the
     questions in the schema are the same sentences by construction. */
  if (faq?.length) {
    graph.push({
      "@type": "FAQPage",
      "@id": `${url}#faq`,
      mainEntity: faq.map((entry) => ({
        "@type": "Question",
        name: entry.question,
        acceptedAnswer: { "@type": "Answer", text: entry.answer },
      })),
    });
  }

  return { "@context": "https://schema.org", "@graph": graph };
}

// --- the block that goes into each head ---------------------------------------

/**
 * The site's Content-Security-Policy, as a meta tag.
 *
 * GitHub Pages serves static files and cannot set a response header, so a meta
 * tag is the only mechanism available here. It is not the same thing:
 * `frame-ancestors` and `X-Frame-Options` are **ignored** in a meta tag, so
 * there is no clickjacking protection on this site and cannot be until it sits
 * behind something that sets headers. SECURITY.md records that.
 *
 * What it does buy: an injected script from any origin other than the three
 * named below will not run, a form cannot be repointed at somebody else's
 * server, `<base>` cannot be rewritten to redirect every relative link, and no
 * plugin content can be embedded at all.
 *
 * What remains permissive, and why:
 * - `'unsafe-inline'` on scripts, because contact.html carries an inline block.
 * - `'unsafe-inline'` on styles, because the markup carries style attributes.
 *
 * What used to be here and is not any more: `'unsafe-eval'`, cdn.tailwindcss.com
 * and unpkg.com. The Tailwind Play CDN compiled classes in the browser, which is
 * what `'unsafe-eval'` was granted for, and unpkg served an unpinned `lucide@latest`
 * for five icons on one page. Both are gone — Preflight is assets/base.css, the
 * utilities are the last block of assets/site.css, and the icons are inline SVG —
 * so the policy no longer has to name a host it cannot vouch for. A CSP naming a
 * third party does not protect against that third party; the fix was to stop
 * needing one. Nothing outside this origin may execute a script now.
 *
 * `style-src` and `font-src` no longer name fonts.googleapis.com or
 * fonts.gstatic.com, and that absence is load-bearing rather than tidying: the
 * typefaces are served from this origin now (assets/fonts.css), because a
 * <link> to Google Fonts sends every visitor's IP address to a US company
 * before the page paints, with no consent asked and no way to refuse. Leaving
 * the hosts in the policy would let that request quietly return. If either
 * host ever needs to come back, the privacy policy has to change with it.
 *
 * googletagmanager.com and google-analytics.com are still named, but nothing
 * reaches them until a visitor turns analytics on: assets/analytics.js is
 * gated behind assets/consent.js. A CSP entry is permission for a request that
 * the code may make, not proof that it makes one.
 */
const CSP = [
  "default-src 'self'",
  "base-uri 'self'",
  "object-src 'none'",
  "form-action 'self'",
  "script-src 'self' 'unsafe-inline' https://www.googletagmanager.com",
  "style-src 'self' 'unsafe-inline'",
  "font-src 'self' data:",
  "img-src 'self' data: https://www.googletagmanager.com https://www.google-analytics.com",
  // os.dakyx.com serves the product prices this site prints. The number is
  // already in the markup and correct; the request only replaces it when the
  // office has moved it since the last publish. No credentials are sent, and
  // the endpoint is above the OS's session middleware, so none could be read.
  "connect-src 'self' https://os.dakyx.com https://www.google-analytics.com https://www.googletagmanager.com",
  "frame-src 'none'",
  "upgrade-insecure-requests",
].join("; ");

function headBlock(page, title, description, faq) {
  const url = `${ORIGIN}${page.path}`;
  const json = JSON.stringify(schemaFor(page, title, description, faq), null, 2);
  const isArticle = Boolean(page.article);

  return [
    BEGIN,
    `<meta http-equiv="Content-Security-Policy" content="${attr(CSP)}">`,
    `<link rel="canonical" href="${url}">`,
    // A transactional page has nothing to offer a search result and should not
    // compete with the page that sells the thing. `noindex` pages are also kept
    // out of the sitemap and disallowed in robots.txt, so all three agree.
    page.noindex
      ? `<meta name="robots" content="noindex, nofollow">`
      : `<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">`,
    `<meta name="keywords" content="${attr(page.keywords)}">`,
    `<meta name="author" content="${COMPANY.name}">`,
    `<meta name="geo.region" content="GH-AH">`,
    `<meta name="geo.placename" content="${COMPANY.locality}">`,
    ...(VERIFICATION.google ? [`<meta name="google-site-verification" content="${attr(VERIFICATION.google)}">`] : []),
    ...(VERIFICATION.bing ? [`<meta name="msvalidate.01" content="${attr(VERIFICATION.bing)}">`] : []),
    ...(VERIFICATION.yandex ? [`<meta name="yandex-verification" content="${attr(VERIFICATION.yandex)}">`] : []),
    ...(VERIFICATION.naver ? [`<meta name="naver-site-verification" content="${attr(VERIFICATION.naver)}">`] : []),
    ``,
    `<meta property="og:type" content="${isArticle ? "article" : "website"}">`,
    ...(isArticle
      ? [
          `<meta property="article:published_time" content="${page.article.published}">`,
          `<meta property="article:section" content="${attr(page.article.section)}">`,
          `<meta property="article:publisher" content="${ORIGIN}/">`,
        ]
      : []),
    `<meta property="og:site_name" content="${COMPANY.name}">`,
    `<meta property="og:locale" content="en_GB">`,
    `<meta property="og:url" content="${url}">`,
    `<meta property="og:title" content="${attr(title)}">`,
    `<meta property="og:description" content="${attr(description)}">`,
    `<meta property="og:image" content="${SHARE_IMAGE}">`,
    `<meta property="og:image:width" content="1200">`,
    `<meta property="og:image:height" content="630">`,
    `<meta property="og:image:type" content="image/png">`,
    `<meta property="og:image:alt" content="${attr(SHARE_IMAGE_ALT)}">`,
    ``,
    `<meta name="twitter:card" content="summary_large_image">`,
    `<meta name="twitter:title" content="${attr(title)}">`,
    `<meta name="twitter:description" content="${attr(description)}">`,
    `<meta name="twitter:image" content="${SHARE_IMAGE}">`,
    `<meta name="twitter:image:alt" content="${attr(SHARE_IMAGE_ALT)}">`,
    ``,
    `<script type="application/ld+json">`,
    json,
    `</script>`,
    ``,
    `<!-- Cookie consent. Must be parsed before analytics.js, which asks it for -->`,
    `<!-- permission and does nothing at all if it is not there. -->`,
    `<link rel="stylesheet" href="/assets/consent.css">`,
    `<script src="/assets/consent.js" defer></script>`,
    `<!-- Does nothing until the GA4 Measurement ID is filled in at the top of -->`,
    `<!-- that file, and nothing then until the visitor allows analytics. -->`,
    `<script src="/assets/analytics.js" defer></script>`,
    END,
  ].join("\n");
}

/** Everything this generator owns is inside the markers, plus the old stray canonical it replaces. */
function applyTo(html, block) {
  let next = html;

  const begin = next.indexOf(BEGIN);
  if (begin !== -1) {
    const end = next.indexOf(END, begin);
    next = next.slice(0, begin) + block + next.slice(end + END.length);
    return next;
  }

  // First run: drop any hand-written canonical, then insert after the title.
  next = next.replace(/^[ \t]*<link rel="canonical"[^>]*>\r?\n/m, "");
  const titleEnd = next.indexOf("</title>");
  if (titleEnd === -1) throw new Error("no <title> to anchor to");
  const at = titleEnd + "</title>".length;
  return `${next.slice(0, at)}\n${block}${next.slice(at)}`;
}

// --- run ----------------------------------------------------------------------

/* Imported by build-breadcrumbs.mjs for the trails, which must be the same
   table the JSON-LD is built from. Importing a module runs it, so everything
   below happens only when this file is the program being run. */
const RUN_DIRECTLY = import.meta.url === pathToFileURL(process.argv[1] ?? "").href;
if (RUN_DIRECTLY) {

const check = process.argv.includes("--check");
const stale = [];

for (const page of PAGES) {
  const html = readFileSync(page.file, "utf8");
  const rawTitle = between(html, "<title>", "</title>");
  const description = between(html, 'name="description" content="', '"');
  if (!rawTitle || !description) throw new Error(`${page.file}: missing a title or a description to build from`);

  const next = applyTo(html, headBlock(page, decode(rawTitle.trim()), decode(description.trim()), readFaq(html)));
  if (next === html) continue;
  if (check) stale.push(page.file);
  else writeFileSync(page.file, next);
}

// robots.txt — one Sitemap line is what actually gets the sitemap found; the
// rest is politeness. Almost nothing is disallowed, because almost nothing here
// is private: the site is thirteen pages meant to be read.
const robots = `# ${ORIGIN}
User-agent: *
Allow: /

# Superseded homepage explorations. Served so old links do not break, but they
# are duplicate copy and must never compete with the real pages in an index.
Disallow: /website-drafts/

# The way in to the website editor. Not secret — it holds nothing but a link to
# the sign-in — but it is not a page anybody should reach from a search result.
Disallow: /admin

# An internal architecture document that was published to the site root by
# accident. Left in place so any link to it still resolves, but it is not a
# page of this website and must not be indexed as one. It also carries a
# noindex of its own — this rule stops it being crawled at all, the meta tag
# covers a crawler that reaches it by a route other than this file.
Disallow: /AGENT_SYSTEM_PLAN.html

${PAGES.filter((page) => page.noindex)
  .map(
    (page) => `
# ${page.noindexReason ?? "Not a page anybody should reach from a search result."}
Disallow: ${page.path}`,
  )
  .join("")}

# AI search and assistant crawlers, named so the welcome is explicit rather
# than inferred. A crawler that finds a group naming it ignores the * group
# entirely, which is why the same Disallow lines are repeated here. Being
# crawled by these is how the site gets cited in ChatGPT search, Claude,
# Perplexity, Copilot, Gemini and Google AI Overviews. The plain-text brief
# for them is ${ORIGIN}/llms.txt.
${AI_CRAWLERS.map((agent) => `User-agent: ${agent}`).join("\n")}
Allow: /
Disallow: /website-drafts/
Disallow: /admin
Disallow: /AGENT_SYSTEM_PLAN.html
${PAGES.filter((page) => page.noindex).map((page) => `Disallow: ${page.path}`).join("\n")}

Sitemap: ${ORIGIN}/sitemap.xml
`;

const today = new Date().toISOString().slice(0, 10);
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${PAGES.filter((page) => !page.noindex).map(
  (page) => `  <url>
    <loc>${ORIGIN}${page.path}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${page.changefreq}</changefreq>
    <priority>${page.priority}</priority>
  </url>`,
).join("\n")}
</urlset>
`;

for (const [file, content] of [
  ["robots.txt", robots],
  ["sitemap.xml", sitemap],
]) {
  const current = (() => {
    try {
      // CRLF on a Windows checkout (core.autocrlf), LF from this script: the
      // same file either way, so compare it as one.
      return readFileSync(file, "utf8").replace(/\r\n/g, "\n");
    } catch {
      return null;
    }
  })();
  // lastmod changes daily; only the shape of the file matters for --check.
  const same = current !== null && current.replace(/<lastmod>[^<]*<\/lastmod>/g, "") === content.replace(/<lastmod>[^<]*<\/lastmod>/g, "");
  if (same) continue;
  if (check) stale.push(file);
  else writeFileSync(file, content);
}

if (check) {
  if (stale.length) {
    console.error(`Out of date — run "node scripts/build-seo.mjs":\n  ${stale.join("\n  ")}`);
    process.exit(1);
  }
  console.log("SEO metadata is up to date.");
} else {
  console.log(`Wrote SEO metadata into ${PAGES.length} pages, plus robots.txt and sitemap.xml.`);
}
}
