/**
 * Website Builder Property Inventory and Specification.
 *
 * Maps every user-facing control across Content, Layout, Style, Interactions,
 * Theme, SEO, Media, and Section tools to its field type, tier requirement,
 * viewport scope, preview action, saved value, and published result.
 */

export type PropertyCategory =
  | "content"
  | "layout"
  | "style"
  | "interactions"
  | "theme"
  | "seo"
  | "media"
  | "sections";

export type TierRequirement = "all" | "pro_or_business";

export type ViewportScope = "all_screens" | "responsive_override" | "global_head";

export type PreviewAction =
  | "live_dom"
  | "live_style"
  | "live_css_vars"
  | "needs_preview_reload"
  | "sandboxed_inert";

export type PropertyInventoryItem = {
  id: string;
  name: string;
  category: PropertyCategory;
  fieldType: string;
  tier: TierRequirement;
  viewportScope: ViewportScope;
  previewAction: PreviewAction;
  savedValueFormat: string;
  publishedResult: string;
  defaultUnit?: string;
  supportedUnits?: string[];
  resetBehavior: string;
  disabledReason?: string;
};

export const PROPERTY_INVENTORY: PropertyInventoryItem[] = [
  // ==========================================
  // 1. Content Controls
  // ==========================================
  {
    id: "content_text",
    name: "Text / Heading",
    category: "content",
    fieldType: "string",
    tier: "all",
    viewportScope: "all_screens",
    previewAction: "live_dom",
    savedValueFormat: "draft.values[id].value",
    publishedResult: "Replaces innerText or innerHTML in published HTML document",
    resetBehavior: "Restores original imported HTML text",
  },
  {
    id: "content_richtext",
    name: "Rich Text",
    category: "content",
    fieldType: "html_string",
    tier: "all",
    viewportScope: "all_screens",
    previewAction: "live_dom",
    savedValueFormat: "draft.values[id].value",
    publishedResult: "Replaces innerHTML preserving bold, links, and line breaks",
    resetBehavior: "Restores original imported HTML markup",
  },
  {
    id: "content_link",
    name: "Link Destination & Label",
    category: "content",
    fieldType: "compound_link",
    tier: "all",
    viewportScope: "all_screens",
    previewAction: "live_dom",
    savedValueFormat: "draft.values[id].href, value, newTab",
    publishedResult: "Updates <a> href, target=\"_blank\", and link text",
    resetBehavior: "Restores original href and link label",
  },
  {
    id: "content_button",
    name: "CTA Button",
    category: "content",
    fieldType: "compound_button",
    tier: "all",
    viewportScope: "all_screens",
    previewAction: "live_dom",
    savedValueFormat: "draft.values[id].href, value, variant, newTab",
    publishedResult: "Updates button/anchor href, styling class, and label",
    resetBehavior: "Restores original button text and URL",
  },
  {
    id: "content_image",
    name: "Image Source & Alt",
    category: "content",
    fieldType: "compound_image",
    tier: "all",
    viewportScope: "all_screens",
    previewAction: "live_dom",
    savedValueFormat: "draft.values[id].value (src), alt, href",
    publishedResult: "Updates <img src alt> and parent anchor href",
    resetBehavior: "Restores original src and alt attributes",
  },
  {
    id: "content_background",
    name: "Container / Section Background Image",
    category: "content",
    fieldType: "image_url",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "background-image: url(...) in element style",
    publishedResult: "Inline CSS or page stylesheet with media queries",
    resetBehavior: "Restores original background image declaration",
  },
  {
    id: "content_icon",
    name: "Icon / SVG Glyph",
    category: "content",
    fieldType: "svg_or_icon",
    tier: "all",
    viewportScope: "all_screens",
    previewAction: "live_dom",
    savedValueFormat: "draft.values[id].icon",
    publishedResult: "Replaces SVG markup or icon class in document",
    resetBehavior: "Restores original SVG markup",
  },
  {
    id: "content_unsupported",
    name: "Preserved Component",
    category: "content",
    fieldType: "readonly_component",
    tier: "all",
    viewportScope: "all_screens",
    previewAction: "sandboxed_inert",
    savedValueFormat: "Exact original HTML bytes preserved untouched",
    publishedResult: "Untouched HTML, iframes, canvas, scripts, and embeds",
    resetBehavior: "Immutable byte preservation",
    disabledReason: "Visual editing is disabled to preserve script execution and embedded structure",
  },

  // ==========================================
  // 2. Layout Controls
  // ==========================================
  {
    id: "layout_display",
    name: "Container Layout",
    category: "layout",
    fieldType: "select",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "display: flex | grid | block",
    publishedResult: "CSS display property declaration",
    resetBehavior: "Restores stylesheet display value",
  },
  {
    id: "layout_content_width_mode",
    name: "Content Width Mode",
    category: "layout",
    fieldType: "select",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "max-width: 1140px; margin: auto (boxed) or width: 100% (full)",
    publishedResult: "CSS max-width and margin rules",
    resetBehavior: "Restores stylesheet width constraints",
  },
  {
    id: "layout_width",
    name: "Width",
    category: "layout",
    fieldType: "length",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "width: <value>",
    publishedResult: "CSS width rule",
    defaultUnit: "px",
    supportedUnits: ["px", "%", "vw"],
    resetBehavior: "Restores stylesheet width",
  },
  {
    id: "layout_min_height",
    name: "Min Height",
    category: "layout",
    fieldType: "length",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "min-height: <value>",
    publishedResult: "CSS min-height rule",
    defaultUnit: "px",
    supportedUnits: ["px", "vh"],
    resetBehavior: "Restores stylesheet min-height",
  },
  {
    id: "layout_flex_direction",
    name: "Direction",
    category: "layout",
    fieldType: "segmented",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "flex-direction: row | column | row-reverse | column-reverse",
    publishedResult: "CSS flex-direction rule",
    resetBehavior: "Restores stylesheet direction",
  },
  {
    id: "layout_justify_content",
    name: "Justify Content",
    category: "layout",
    fieldType: "segmented",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "justify-content: flex-start | center | flex-end | space-between | space-around | space-evenly",
    publishedResult: "CSS justify-content rule",
    resetBehavior: "Restores stylesheet justify-content",
  },
  {
    id: "layout_align_items",
    name: "Align Items",
    category: "layout",
    fieldType: "segmented",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "align-items: stretch | flex-start | center | flex-end | baseline",
    publishedResult: "CSS align-items rule",
    resetBehavior: "Restores stylesheet align-items",
  },
  {
    id: "layout_column_gap",
    name: "Column Gap",
    category: "layout",
    fieldType: "length",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "column-gap: <value>",
    publishedResult: "CSS column-gap rule",
    defaultUnit: "px",
    supportedUnits: ["px", "%", "rem"],
    resetBehavior: "Restores stylesheet column gap",
  },
  {
    id: "layout_row_gap",
    name: "Row Gap",
    category: "layout",
    fieldType: "length",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "row-gap: <value>",
    publishedResult: "CSS row-gap rule",
    defaultUnit: "px",
    supportedUnits: ["px", "%", "rem"],
    resetBehavior: "Restores stylesheet row gap",
  },
  {
    id: "layout_flex_wrap",
    name: "Wrap",
    category: "layout",
    fieldType: "segmented",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "flex-wrap: nowrap | wrap",
    publishedResult: "CSS flex-wrap rule",
    resetBehavior: "Restores stylesheet wrap",
  },
  {
    id: "layout_grid_template_columns",
    name: "Grid Columns",
    category: "layout",
    fieldType: "text",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "grid-template-columns: <value>",
    publishedResult: "CSS grid-template-columns rule",
    resetBehavior: "Restores stylesheet grid columns",
  },
  {
    id: "layout_grid_template_rows",
    name: "Grid Rows",
    category: "layout",
    fieldType: "text",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "grid-template-rows: <value>",
    publishedResult: "CSS grid-template-rows rule",
    resetBehavior: "Restores stylesheet grid rows",
  },
  {
    id: "layout_align_self",
    name: "Align Self",
    category: "layout",
    fieldType: "select",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "align-self: <value>",
    publishedResult: "CSS align-self rule",
    resetBehavior: "Restores stylesheet align-self",
  },
  {
    id: "layout_flex_grow",
    name: "Flex Grow",
    category: "layout",
    fieldType: "number",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "flex-grow: <value>",
    publishedResult: "CSS flex-grow rule",
    resetBehavior: "Restores stylesheet flex grow",
  },
  {
    id: "layout_flex_shrink",
    name: "Flex Shrink",
    category: "layout",
    fieldType: "number",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "flex-shrink: <value>",
    publishedResult: "CSS flex-shrink rule",
    resetBehavior: "Restores stylesheet flex shrink",
  },
  {
    id: "layout_order",
    name: "Flex / Grid Order",
    category: "layout",
    fieldType: "number",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "order: <value>",
    publishedResult: "CSS order rule",
    resetBehavior: "Restores stylesheet order",
  },

  // ==========================================
  // 3. Style Controls
  // ==========================================
  {
    id: "style_padding",
    name: "Padding",
    category: "style",
    fieldType: "quad_length",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "padding-top, padding-right, padding-bottom, padding-left",
    publishedResult: "CSS padding declarations",
    defaultUnit: "px",
    supportedUnits: ["px", "%", "em", "rem"],
    resetBehavior: "Restores stylesheet padding",
  },
  {
    id: "style_margin",
    name: "Margin",
    category: "style",
    fieldType: "quad_length",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "margin-top, margin-right, margin-bottom, margin-left",
    publishedResult: "CSS margin declarations",
    defaultUnit: "px",
    supportedUnits: ["px", "%", "em", "rem"],
    resetBehavior: "Restores stylesheet margin",
  },
  {
    id: "style_font_family",
    name: "Font Family",
    category: "style",
    fieldType: "select",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "font-family: <stack>",
    publishedResult: "CSS font-family declaration",
    resetBehavior: "Restores stylesheet font family",
  },
  {
    id: "style_font_size",
    name: "Font Size",
    category: "style",
    fieldType: "length",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "font-size: <value>",
    publishedResult: "CSS font-size declaration",
    defaultUnit: "px",
    supportedUnits: ["px", "rem", "em", "%"],
    resetBehavior: "Restores stylesheet font size",
  },
  {
    id: "style_color",
    name: "Text Colour",
    category: "style",
    fieldType: "color",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "color: <hex_or_rgba>",
    publishedResult: "CSS color declaration",
    resetBehavior: "Restores stylesheet text colour",
  },
  {
    id: "style_font_weight",
    name: "Font Weight",
    category: "style",
    fieldType: "select",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "font-weight: 300..900",
    publishedResult: "CSS font-weight declaration",
    resetBehavior: "Restores stylesheet font weight",
  },
  {
    id: "style_font_style",
    name: "Font Style (Italic)",
    category: "style",
    fieldType: "toggle",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "font-style: italic | normal",
    publishedResult: "CSS font-style declaration",
    resetBehavior: "Restores stylesheet font style",
  },
  {
    id: "style_text_decoration",
    name: "Text Decoration",
    category: "style",
    fieldType: "toggle",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "text-decoration: underline | line-through | none",
    publishedResult: "CSS text-decoration declaration",
    resetBehavior: "Restores stylesheet text decoration",
  },
  {
    id: "style_text_align",
    name: "Text Align",
    category: "style",
    fieldType: "segmented",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "text-align: left | center | right | justify",
    publishedResult: "CSS text-align declaration",
    resetBehavior: "Restores stylesheet text alignment",
  },
  {
    id: "style_line_height",
    name: "Leading (Line Height)",
    category: "style",
    fieldType: "length",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "line-height: <value>",
    publishedResult: "CSS line-height declaration",
    defaultUnit: "px",
    supportedUnits: ["px", "rem", "em", "%"],
    resetBehavior: "Restores stylesheet line height",
  },
  {
    id: "style_letter_spacing",
    name: "Tracking (Letter Spacing)",
    category: "style",
    fieldType: "length",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "letter-spacing: <value>",
    publishedResult: "CSS letter-spacing declaration",
    defaultUnit: "px",
    supportedUnits: ["px", "rem", "em"],
    resetBehavior: "Restores stylesheet letter spacing",
  },
  {
    id: "style_text_transform",
    name: "Case (Text Transform)",
    category: "style",
    fieldType: "select",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "text-transform: uppercase | lowercase | capitalize | none",
    publishedResult: "CSS text-transform declaration",
    resetBehavior: "Restores stylesheet text transform",
  },
  {
    id: "style_background_color",
    name: "Background Colour",
    category: "style",
    fieldType: "color",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "background-color: <value>",
    publishedResult: "CSS background-color declaration",
    resetBehavior: "Restores stylesheet background colour",
  },
  {
    id: "style_background_size",
    name: "Background Size Resolution",
    category: "style",
    fieldType: "select",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "background-size: cover | contain | auto | 100% 100%",
    publishedResult: "CSS background-size declaration",
    resetBehavior: "Restores stylesheet background size",
  },
  {
    id: "style_background_position",
    name: "Background Position",
    category: "style",
    fieldType: "select",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "background-position: center | top | bottom | left | right",
    publishedResult: "CSS background-position declaration",
    resetBehavior: "Restores stylesheet background position",
  },
  {
    id: "style_border",
    name: "Border",
    category: "style",
    fieldType: "compound_border",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "border: <width>px <style> <color>",
    publishedResult: "CSS border declaration",
    resetBehavior: "Restores stylesheet border",
  },
  {
    id: "style_border_radius",
    name: "Corner Radius",
    category: "style",
    fieldType: "length",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "border-radius: <value>",
    publishedResult: "CSS border-radius declaration",
    defaultUnit: "px",
    supportedUnits: ["px", "%", "rem"],
    resetBehavior: "Restores stylesheet corner radius",
  },
  {
    id: "style_opacity",
    name: "Opacity",
    category: "style",
    fieldType: "number",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "opacity: 0..1",
    publishedResult: "CSS opacity declaration",
    resetBehavior: "Restores stylesheet opacity (1.0)",
  },
  {
    id: "style_box_shadow",
    name: "Box Shadow",
    category: "style",
    fieldType: "compound_shadow",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "box-shadow: <x> <y> <blur> <spread> <color>",
    publishedResult: "CSS box-shadow declaration",
    resetBehavior: "Restores stylesheet box shadow",
  },
  {
    id: "style_text_shadow",
    name: "Text Shadow",
    category: "style",
    fieldType: "compound_shadow",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "text-shadow: <x> <y> <blur> <color>",
    publishedResult: "CSS text-shadow declaration",
    resetBehavior: "Restores stylesheet text shadow",
  },
  {
    id: "style_filter",
    name: "Filter",
    category: "style",
    fieldType: "text",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "filter: blur(...) brightness(...)",
    publishedResult: "CSS filter declaration",
    resetBehavior: "Restores stylesheet filter",
  },
  {
    id: "style_transform",
    name: "Transform",
    category: "style",
    fieldType: "compound_transform",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "transform: translate(...) rotate(...) scale(...)",
    publishedResult: "CSS transform declaration",
    resetBehavior: "Restores stylesheet transform",
  },
  {
    id: "style_position",
    name: "Position",
    category: "style",
    fieldType: "select",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "position: static | relative | absolute | fixed | sticky",
    publishedResult: "CSS position declaration",
    resetBehavior: "Restores stylesheet position",
  },
  {
    id: "style_offsets",
    name: "Position Offsets",
    category: "style",
    fieldType: "quad_length",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "top, right, bottom, left",
    publishedResult: "CSS position offset declarations",
    defaultUnit: "px",
    supportedUnits: ["px", "%", "vh", "vw"],
    resetBehavior: "Restores stylesheet offsets",
  },
  {
    id: "style_z_index",
    name: "Stack Order (Z-Index)",
    category: "style",
    fieldType: "number",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "z-index: <value>",
    publishedResult: "CSS z-index declaration",
    resetBehavior: "Restores stylesheet stacking order",
  },

  // ==========================================
  // 4. Interactions Controls
  // ==========================================
  {
    id: "interactions_hover",
    name: "Hover Styles",
    category: "interactions",
    fieldType: "style_map",
    tier: "all",
    viewportScope: "all_screens",
    previewAction: "live_style",
    savedValueFormat: "data-dw-hover style attribute and page stylesheet",
    publishedResult: ":hover CSS rule in page stylesheet",
    resetBehavior: "Removes hover state override",
  },
  {
    id: "interactions_transition",
    name: "Transitions",
    category: "interactions",
    fieldType: "text",
    tier: "all",
    viewportScope: "all_screens",
    previewAction: "live_style",
    savedValueFormat: "transition: <value>",
    publishedResult: "CSS transition rule",
    defaultUnit: "s",
    supportedUnits: ["s", "ms"],
    resetBehavior: "Restores stylesheet transition",
  },

  // ==========================================
  // 5. Theme Controls
  // ==========================================
  {
    id: "theme_palette_colors",
    name: "Global Color Palette",
    category: "theme",
    fieldType: "color_array",
    tier: "pro_or_business",
    viewportScope: "global_head",
    previewAction: "live_css_vars",
    savedValueFormat: "page.theme.colours in SitePage data",
    publishedResult: ":root CSS custom properties",
    resetBehavior: "Restores website default palette",
    disabledReason: "Global Theme Color Palette is unlocked on Pro and Business plans",
  },
  {
    id: "theme_surface_background",
    name: "Page Surface Controls",
    category: "theme",
    fieldType: "color",
    tier: "pro_or_business",
    viewportScope: "global_head",
    previewAction: "live_css_vars",
    savedValueFormat: "page.theme.surfaceBg in SitePage data",
    publishedResult: "body background styling and CSS custom properties",
    resetBehavior: "Restores default surface color",
    disabledReason: "Page Surface Controls are unlocked on Pro and Business plans",
  },

  // ==========================================
  // 6. SEO Controls
  // ==========================================
  {
    id: "seo_page_title",
    name: "Page Title",
    category: "seo",
    fieldType: "string",
    tier: "all",
    viewportScope: "global_head",
    previewAction: "needs_preview_reload",
    savedValueFormat: "page.title and draft.values[\"title\"].value",
    publishedResult: "<title>...</title> in HTML <head>",
    resetBehavior: "Restores original HTML title",
  },
  {
    id: "seo_meta_description",
    name: "Meta Description",
    category: "seo",
    fieldType: "string",
    tier: "all",
    viewportScope: "global_head",
    previewAction: "needs_preview_reload",
    savedValueFormat: "draft.values[\"meta.description\"].value",
    publishedResult: "<meta name=\"description\" content=\"...\">",
    resetBehavior: "Restores original HTML meta description",
  },
  {
    id: "seo_og_title",
    name: "OpenGraph Title",
    category: "seo",
    fieldType: "string",
    tier: "pro_or_business",
    viewportScope: "global_head",
    previewAction: "needs_preview_reload",
    savedValueFormat: "draft.values[\"meta.og:title\"].value",
    publishedResult: "<meta property=\"og:title\" content=\"...\">",
    resetBehavior: "Restores original og:title",
    disabledReason: "SEO Inspector & Alt-Text Auto-Fixer is available starting on Pro and Business plans",
  },
  {
    id: "seo_og_description",
    name: "OpenGraph Description",
    category: "seo",
    fieldType: "string",
    tier: "pro_or_business",
    viewportScope: "global_head",
    previewAction: "needs_preview_reload",
    savedValueFormat: "draft.values[\"meta.og:description\"].value",
    publishedResult: "<meta property=\"og:description\" content=\"...\">",
    resetBehavior: "Restores original og:description",
    disabledReason: "SEO Inspector & Alt-Text Auto-Fixer is available starting on Pro and Business plans",
  },
  {
    id: "seo_og_image",
    name: "OpenGraph Social Image",
    category: "seo",
    fieldType: "image_url",
    tier: "pro_or_business",
    viewportScope: "global_head",
    previewAction: "needs_preview_reload",
    savedValueFormat: "draft.values[\"meta.og:image\"].value",
    publishedResult: "<meta property=\"og:image\" content=\"...\">",
    resetBehavior: "Restores original og:image",
    disabledReason: "SEO Inspector & Alt-Text Auto-Fixer is available starting on Pro and Business plans",
  },
  {
    id: "seo_alt_text_autofixer",
    name: "Alt-Text Auto-Fixer",
    category: "seo",
    fieldType: "action",
    tier: "pro_or_business",
    viewportScope: "all_screens",
    previewAction: "live_dom",
    savedValueFormat: "draft.values[id].alt",
    publishedResult: "Updated alt=\"...\" attributes across page images",
    resetBehavior: "Restores original image alt attributes",
    disabledReason: "Alt-Text Auto-Fixer is available on Pro and Business plans",
  },

  // ==========================================
  // 7. Media Controls
  // ==========================================
  {
    id: "media_image_library",
    name: "Asset Library & Upload",
    category: "media",
    fieldType: "asset_reference",
    tier: "all",
    viewportScope: "all_screens",
    previewAction: "live_dom",
    savedValueFormat: "Hosted asset URL (/sites/:siteId/raw/assets/...) or base64",
    publishedResult: "Replaced asset path or embedded URL in published HTML",
    resetBehavior: "Restores original image reference",
  },
  {
    id: "media_image_framing",
    name: "Image Framing & Crop",
    category: "media",
    fieldType: "compound_framing",
    tier: "all",
    viewportScope: "all_screens",
    previewAction: "live_dom",
    savedValueFormat: "object-fit: ...; object-position: ...",
    publishedResult: "CSS framing properties in style attribute",
    resetBehavior: "Restores original framing",
  },

  // ==========================================
  // 8. Sections & Structure Controls
  // ==========================================
  {
    id: "section_reorder",
    name: "Reorder Layers",
    category: "sections",
    fieldType: "structure_action",
    tier: "all",
    viewportScope: "all_screens",
    previewAction: "needs_preview_reload",
    savedValueFormat: "Reordered HTML DOM node sequence",
    publishedResult: "Permuted element markup in HTML document",
    resetBehavior: "Undo restores previous element order",
  },
  {
    id: "section_duplicate",
    name: "Duplicate / Add Item",
    category: "sections",
    fieldType: "structure_action",
    tier: "all",
    viewportScope: "all_screens",
    previewAction: "needs_preview_reload",
    savedValueFormat: "Cloned HTML DOM node with unique child IDs",
    publishedResult: "New duplicated element inserted into HTML",
    resetBehavior: "Undo removes duplicated element",
  },
  {
    id: "section_remove",
    name: "Remove Element",
    category: "sections",
    fieldType: "structure_action",
    tier: "all",
    viewportScope: "all_screens",
    previewAction: "needs_preview_reload",
    savedValueFormat: "Removed HTML DOM node",
    publishedResult: "Element omitted from published HTML",
    resetBehavior: "Undo restores removed element",
  },
  {
    id: "section_visibility",
    name: "Toggle Visibility",
    category: "sections",
    fieldType: "toggle",
    tier: "all",
    viewportScope: "responsive_override",
    previewAction: "live_style",
    savedValueFormat: "display: none",
    publishedResult: "CSS display: none on element",
    resetBehavior: "Restores element display",
  },
];

/**
 * Filter inventory items by functional category.
 */
export function getPropertyInventoryByCategory(category: PropertyCategory): PropertyInventoryItem[] {
  return PROPERTY_INVENTORY.filter((item) => item.category === category);
}

/**
 * Find a specific control by its ID or property name.
 */
export function findPropertyControl(id: string): PropertyInventoryItem | undefined {
  return PROPERTY_INVENTORY.find((item) => item.id === id || item.id.endsWith(`_${id}`));
}

/**
 * Validate that every property has a defined category, tier, preview action,
 * and valid unit where applicable.
 */
export function auditPropertyInventory(): {
  total: number;
  byCategory: Record<PropertyCategory, number>;
  lockedFeatures: number;
  reloadRequired: number;
  valid: boolean;
} {
  const byCategory: Record<PropertyCategory, number> = {
    content: 0,
    layout: 0,
    style: 0,
    interactions: 0,
    theme: 0,
    seo: 0,
    media: 0,
    sections: 0,
  };

  let lockedFeatures = 0;
  let reloadRequired = 0;

  for (const item of PROPERTY_INVENTORY) {
    byCategory[item.category] = (byCategory[item.category] ?? 0) + 1;
    if (item.tier === "pro_or_business") lockedFeatures++;
    if (item.previewAction === "needs_preview_reload") reloadRequired++;
  }

  return {
    total: PROPERTY_INVENTORY.length,
    byCategory,
    lockedFeatures,
    reloadRequired,
    valid: PROPERTY_INVENTORY.length > 0,
  };
}
